/* Country dataset shared by Bayrak Bilmece, Başkent Bilmece, Worldle.
 * Each entry:
 *   code   : ISO-2 (uppercase)
 *   flag   : flag emoji
 *   name   : Turkish name
 *   capital: capital (Turkish)
 *   lat    : approximate centroid latitude
 *   lon    : approximate centroid longitude
 *   region : continent (asia|europe|africa|america|oceania)
 */
window.COUNTRIES = [
  { code: "TR", flag: "🇹🇷", name: "Türkiye",          capital: "Ankara",            lat: 39.0,  lon: 35.0,  region: "asia" },
  { code: "DE", flag: "🇩🇪", name: "Almanya",          capital: "Berlin",            lat: 51.0,  lon: 9.0,   region: "europe" },
  { code: "FR", flag: "🇫🇷", name: "Fransa",           capital: "Paris",             lat: 46.0,  lon: 2.0,   region: "europe" },
  { code: "IT", flag: "🇮🇹", name: "İtalya",           capital: "Roma",              lat: 42.5,  lon: 12.5,  region: "europe" },
  { code: "ES", flag: "🇪🇸", name: "İspanya",          capital: "Madrid",            lat: 40.0,  lon: -4.0,  region: "europe" },
  { code: "PT", flag: "🇵🇹", name: "Portekiz",         capital: "Lizbon",            lat: 39.5,  lon: -8.0,  region: "europe" },
  { code: "GB", flag: "🇬🇧", name: "İngiltere",        capital: "Londra",            lat: 54.0,  lon: -2.0,  region: "europe" },
  { code: "IE", flag: "🇮🇪", name: "İrlanda",          capital: "Dublin",            lat: 53.0,  lon: -8.0,  region: "europe" },
  { code: "NL", flag: "🇳🇱", name: "Hollanda",         capital: "Amsterdam",         lat: 52.5,  lon: 5.5,   region: "europe" },
  { code: "BE", flag: "🇧🇪", name: "Belçika",          capital: "Brüksel",           lat: 50.8,  lon: 4.5,   region: "europe" },
  { code: "CH", flag: "🇨🇭", name: "İsviçre",          capital: "Bern",              lat: 47.0,  lon: 8.0,   region: "europe" },
  { code: "AT", flag: "🇦🇹", name: "Avusturya",        capital: "Viyana",            lat: 47.5,  lon: 14.5,  region: "europe" },
  { code: "PL", flag: "🇵🇱", name: "Polonya",          capital: "Varşova",           lat: 52.0,  lon: 19.0,  region: "europe" },
  { code: "CZ", flag: "🇨🇿", name: "Çek Cumhuriyeti",  capital: "Prag",              lat: 49.7,  lon: 15.5,  region: "europe" },
  { code: "HU", flag: "🇭🇺", name: "Macaristan",       capital: "Budapeşte",         lat: 47.0,  lon: 20.0,  region: "europe" },
  { code: "RO", flag: "🇷🇴", name: "Romanya",          capital: "Bükreş",            lat: 46.0,  lon: 25.0,  region: "europe" },
  { code: "BG", flag: "🇧🇬", name: "Bulgaristan",      capital: "Sofya",             lat: 43.0,  lon: 25.0,  region: "europe" },
  { code: "GR", flag: "🇬🇷", name: "Yunanistan",       capital: "Atina",             lat: 39.0,  lon: 22.0,  region: "europe" },
  { code: "RS", flag: "🇷🇸", name: "Sırbistan",        capital: "Belgrad",           lat: 44.0,  lon: 21.0,  region: "europe" },
  { code: "HR", flag: "🇭🇷", name: "Hırvatistan",      capital: "Zagreb",            lat: 45.5,  lon: 16.0,  region: "europe" },
  { code: "BA", flag: "🇧🇦", name: "Bosna-Hersek",     capital: "Saraybosna",        lat: 44.0,  lon: 18.0,  region: "europe" },
  { code: "AL", flag: "🇦🇱", name: "Arnavutluk",       capital: "Tiran",             lat: 41.0,  lon: 20.0,  region: "europe" },
  { code: "RU", flag: "🇷🇺", name: "Rusya",            capital: "Moskova",           lat: 60.0,  lon: 100.0, region: "europe" },
  { code: "UA", flag: "🇺🇦", name: "Ukrayna",          capital: "Kiev",              lat: 49.0,  lon: 32.0,  region: "europe" },
  { code: "BY", flag: "🇧🇾", name: "Belarus",          capital: "Minsk",             lat: 53.7,  lon: 27.9,  region: "europe" },
  { code: "FI", flag: "🇫🇮", name: "Finlandiya",       capital: "Helsinki",          lat: 64.0,  lon: 26.0,  region: "europe" },
  { code: "SE", flag: "🇸🇪", name: "İsveç",            capital: "Stockholm",         lat: 62.0,  lon: 15.0,  region: "europe" },
  { code: "NO", flag: "🇳🇴", name: "Norveç",           capital: "Oslo",              lat: 62.0,  lon: 10.0,  region: "europe" },
  { code: "DK", flag: "🇩🇰", name: "Danimarka",        capital: "Kopenhag",          lat: 56.0,  lon: 10.0,  region: "europe" },
  { code: "IS", flag: "🇮🇸", name: "İzlanda",          capital: "Reykjavík",         lat: 65.0,  lon: -18.0, region: "europe" },

  { code: "JP", flag: "🇯🇵", name: "Japonya",          capital: "Tokyo",             lat: 36.0,  lon: 138.0, region: "asia" },
  { code: "KR", flag: "🇰🇷", name: "Güney Kore",       capital: "Seul",              lat: 37.0,  lon: 127.5, region: "asia" },
  { code: "CN", flag: "🇨🇳", name: "Çin",              capital: "Pekin",             lat: 35.0,  lon: 105.0, region: "asia" },
  { code: "IN", flag: "🇮🇳", name: "Hindistan",        capital: "Yeni Delhi",        lat: 20.0,  lon: 77.0,  region: "asia" },
  { code: "PK", flag: "🇵🇰", name: "Pakistan",         capital: "İslamabad",         lat: 30.0,  lon: 70.0,  region: "asia" },
  { code: "IR", flag: "🇮🇷", name: "İran",             capital: "Tahran",            lat: 32.0,  lon: 53.0,  region: "asia" },
  { code: "IQ", flag: "🇮🇶", name: "Irak",             capital: "Bağdat",            lat: 33.0,  lon: 44.0,  region: "asia" },
  { code: "SY", flag: "🇸🇾", name: "Suriye",           capital: "Şam",               lat: 35.0,  lon: 38.0,  region: "asia" },
  { code: "SA", flag: "🇸🇦", name: "Suudi Arabistan",  capital: "Riyad",             lat: 25.0,  lon: 45.0,  region: "asia" },
  { code: "AE", flag: "🇦🇪", name: "BAE",              capital: "Abu Dabi",          lat: 24.0,  lon: 54.0,  region: "asia" },
  { code: "IL", flag: "🇮🇱", name: "İsrail",           capital: "Kudüs",             lat: 31.5,  lon: 34.8,  region: "asia" },
  { code: "JO", flag: "🇯🇴", name: "Ürdün",            capital: "Amman",             lat: 31.0,  lon: 36.0,  region: "asia" },
  { code: "LB", flag: "🇱🇧", name: "Lübnan",           capital: "Beyrut",            lat: 33.8,  lon: 35.8,  region: "asia" },
  { code: "AZ", flag: "🇦🇿", name: "Azerbaycan",       capital: "Bakü",              lat: 40.5,  lon: 47.5,  region: "asia" },
  { code: "GE", flag: "🇬🇪", name: "Gürcistan",        capital: "Tiflis",            lat: 42.0,  lon: 43.5,  region: "asia" },
  { code: "AM", flag: "🇦🇲", name: "Ermenistan",       capital: "Erivan",            lat: 40.0,  lon: 45.0,  region: "asia" },
  { code: "KZ", flag: "🇰🇿", name: "Kazakistan",       capital: "Astana",            lat: 48.0,  lon: 68.0,  region: "asia" },
  { code: "UZ", flag: "🇺🇿", name: "Özbekistan",       capital: "Taşkent",           lat: 41.0,  lon: 64.0,  region: "asia" },
  { code: "AF", flag: "🇦🇫", name: "Afganistan",       capital: "Kabil",             lat: 33.0,  lon: 65.0,  region: "asia" },
  { code: "TH", flag: "🇹🇭", name: "Tayland",          capital: "Bangkok",           lat: 15.0,  lon: 101.0, region: "asia" },
  { code: "VN", flag: "🇻🇳", name: "Vietnam",          capital: "Hanoi",             lat: 16.0,  lon: 106.0, region: "asia" },
  { code: "ID", flag: "🇮🇩", name: "Endonezya",        capital: "Cakarta",           lat: -5.0,  lon: 120.0, region: "asia" },
  { code: "PH", flag: "🇵🇭", name: "Filipinler",       capital: "Manila",            lat: 13.0,  lon: 122.0, region: "asia" },
  { code: "MY", flag: "🇲🇾", name: "Malezya",          capital: "Kuala Lumpur",      lat: 2.5,   lon: 112.5, region: "asia" },
  { code: "SG", flag: "🇸🇬", name: "Singapur",         capital: "Singapur",          lat: 1.3,   lon: 103.8, region: "asia" },

  { code: "EG", flag: "🇪🇬", name: "Mısır",            capital: "Kahire",            lat: 27.0,  lon: 30.0,  region: "africa" },
  { code: "LY", flag: "🇱🇾", name: "Libya",            capital: "Trablus",           lat: 25.0,  lon: 17.0,  region: "africa" },
  { code: "TN", flag: "🇹🇳", name: "Tunus",            capital: "Tunus",             lat: 34.0,  lon: 9.0,   region: "africa" },
  { code: "DZ", flag: "🇩🇿", name: "Cezayir",          capital: "Cezayir",           lat: 28.0,  lon: 3.0,   region: "africa" },
  { code: "MA", flag: "🇲🇦", name: "Fas",              capital: "Rabat",             lat: 32.0,  lon: -5.0,  region: "africa" },
  { code: "ZA", flag: "🇿🇦", name: "Güney Afrika",     capital: "Pretoria",          lat: -29.0, lon: 24.0,  region: "africa" },
  { code: "NG", flag: "🇳🇬", name: "Nijerya",          capital: "Abuja",             lat: 10.0,  lon: 8.0,   region: "africa" },
  { code: "KE", flag: "🇰🇪", name: "Kenya",            capital: "Nairobi",           lat: 1.0,   lon: 38.0,  region: "africa" },
  { code: "ET", flag: "🇪🇹", name: "Etiyopya",         capital: "Addis Ababa",       lat: 8.0,   lon: 38.0,  region: "africa" },
  { code: "SN", flag: "🇸🇳", name: "Senegal",          capital: "Dakar",             lat: 14.0,  lon: -14.0, region: "africa" },
  { code: "GH", flag: "🇬🇭", name: "Gana",             capital: "Accra",             lat: 8.0,   lon: -2.0,  region: "africa" },

  { code: "US", flag: "🇺🇸", name: "ABD",              capital: "Washington",        lat: 38.0,  lon: -97.0, region: "america" },
  { code: "CA", flag: "🇨🇦", name: "Kanada",           capital: "Ottawa",            lat: 60.0,  lon: -95.0, region: "america" },
  { code: "MX", flag: "🇲🇽", name: "Meksika",          capital: "Meksiko",           lat: 23.0,  lon: -102.0,region: "america" },
  { code: "BR", flag: "🇧🇷", name: "Brezilya",         capital: "Brasilia",          lat: -10.0, lon: -55.0, region: "america" },
  { code: "AR", flag: "🇦🇷", name: "Arjantin",         capital: "Buenos Aires",      lat: -34.0, lon: -64.0, region: "america" },
  { code: "CL", flag: "🇨🇱", name: "Şili",             capital: "Santiago",          lat: -30.0, lon: -71.0, region: "america" },
  { code: "PE", flag: "🇵🇪", name: "Peru",             capital: "Lima",              lat: -10.0, lon: -76.0, region: "america" },
  { code: "CO", flag: "🇨🇴", name: "Kolombiya",        capital: "Bogotá",            lat: 4.0,   lon: -72.0, region: "america" },
  { code: "VE", flag: "🇻🇪", name: "Venezuela",        capital: "Karakas",           lat: 8.0,   lon: -66.0, region: "america" },
  { code: "CU", flag: "🇨🇺", name: "Küba",             capital: "Havana",            lat: 22.0,  lon: -79.5, region: "america" },

  { code: "AU", flag: "🇦🇺", name: "Avustralya",       capital: "Canberra",          lat: -27.0, lon: 133.0, region: "oceania" },
  { code: "NZ", flag: "🇳🇿", name: "Yeni Zelanda",     capital: "Wellington",        lat: -41.0, lon: 174.0, region: "oceania" }
];
