/* Country dataset shared by Bayrak Bilmece, Başkent Bilmece, Worldle.
 * 180+ countries with code, flag, Turkish name, capital, lat/lon, region.
 * Each entry:
 *   code   : ISO-2 (uppercase)
 *   flag   : flag emoji
 *   name   : Turkish name
 *   capital: capital (Turkish)
 *   lat    : approximate centroid latitude
 *   lon    : approximate centroid longitude
 *   region : continent (asia|europe|africa|america|oceania)
 */
window.COUNTRIES = [
  // ============================================================
  // EUROPE (44)
  // ============================================================
  { code: "TR", flag: "🇹🇷", name: "Türkiye",         capital: "Ankara",            lat: 39.0,  lon: 35.0,  region: "asia" },
  { code: "DE", flag: "🇩🇪", name: "Almanya",         capital: "Berlin",            lat: 51.0,  lon: 9.0,   region: "europe" },
  { code: "FR", flag: "🇫🇷", name: "Fransa",          capital: "Paris",             lat: 46.0,  lon: 2.0,   region: "europe" },
  { code: "IT", flag: "🇮🇹", name: "İtalya",          capital: "Roma",              lat: 42.5,  lon: 12.5,  region: "europe" },
  { code: "ES", flag: "🇪🇸", name: "İspanya",         capital: "Madrid",            lat: 40.0,  lon: -4.0,  region: "europe" },
  { code: "PT", flag: "🇵🇹", name: "Portekiz",        capital: "Lizbon",            lat: 39.5,  lon: -8.0,  region: "europe" },
  { code: "GB", flag: "🇬🇧", name: "İngiltere",       capital: "Londra",            lat: 54.0,  lon: -2.0,  region: "europe" },
  { code: "IE", flag: "🇮🇪", name: "İrlanda",         capital: "Dublin",            lat: 53.0,  lon: -8.0,  region: "europe" },
  { code: "NL", flag: "🇳🇱", name: "Hollanda",        capital: "Amsterdam",         lat: 52.5,  lon: 5.5,   region: "europe" },
  { code: "BE", flag: "🇧🇪", name: "Belçika",         capital: "Brüksel",           lat: 50.8,  lon: 4.5,   region: "europe" },
  { code: "CH", flag: "🇨🇭", name: "İsviçre",         capital: "Bern",              lat: 47.0,  lon: 8.0,   region: "europe" },
  { code: "AT", flag: "🇦🇹", name: "Avusturya",       capital: "Viyana",            lat: 47.5,  lon: 14.5,  region: "europe" },
  { code: "PL", flag: "🇵🇱", name: "Polonya",         capital: "Varşova",           lat: 52.0,  lon: 19.0,  region: "europe" },
  { code: "CZ", flag: "🇨🇿", name: "Çekya",           capital: "Prag",              lat: 49.7,  lon: 15.5,  region: "europe" },
  { code: "SK", flag: "🇸🇰", name: "Slovakya",        capital: "Bratislava",        lat: 48.7,  lon: 19.7,  region: "europe" },
  { code: "HU", flag: "🇭🇺", name: "Macaristan",      capital: "Budapeşte",         lat: 47.0,  lon: 20.0,  region: "europe" },
  { code: "RO", flag: "🇷🇴", name: "Romanya",         capital: "Bükreş",            lat: 46.0,  lon: 25.0,  region: "europe" },
  { code: "BG", flag: "🇧🇬", name: "Bulgaristan",     capital: "Sofya",             lat: 43.0,  lon: 25.0,  region: "europe" },
  { code: "GR", flag: "🇬🇷", name: "Yunanistan",      capital: "Atina",             lat: 39.0,  lon: 22.0,  region: "europe" },
  { code: "RS", flag: "🇷🇸", name: "Sırbistan",       capital: "Belgrad",           lat: 44.0,  lon: 21.0,  region: "europe" },
  { code: "HR", flag: "🇭🇷", name: "Hırvatistan",     capital: "Zagreb",            lat: 45.5,  lon: 16.0,  region: "europe" },
  { code: "BA", flag: "🇧🇦", name: "Bosna-Hersek",    capital: "Saraybosna",        lat: 44.0,  lon: 18.0,  region: "europe" },
  { code: "SI", flag: "🇸🇮", name: "Slovenya",        capital: "Ljubljana",         lat: 46.1,  lon: 15.0,  region: "europe" },
  { code: "ME", flag: "🇲🇪", name: "Karadağ",         capital: "Podgoritsa",        lat: 42.7,  lon: 19.4,  region: "europe" },
  { code: "MK", flag: "🇲🇰", name: "Kuzey Makedonya", capital: "Üsküp",             lat: 41.6,  lon: 21.7,  region: "europe" },
  { code: "XK", flag: "🇽🇰", name: "Kosova",          capital: "Priştine",          lat: 42.6,  lon: 20.9,  region: "europe" },
  { code: "AL", flag: "🇦🇱", name: "Arnavutluk",      capital: "Tiran",             lat: 41.0,  lon: 20.0,  region: "europe" },
  { code: "RU", flag: "🇷🇺", name: "Rusya",           capital: "Moskova",           lat: 66.4,  lon: 94.3,  region: "europe" },
  { code: "UA", flag: "🇺🇦", name: "Ukrayna",         capital: "Kiev",              lat: 49.0,  lon: 32.0,  region: "europe" },
  { code: "BY", flag: "🇧🇾", name: "Belarus",         capital: "Minsk",             lat: 53.7,  lon: 27.9,  region: "europe" },
  { code: "MD", flag: "🇲🇩", name: "Moldova",         capital: "Kişinev",           lat: 47.4,  lon: 28.4,  region: "europe" },
  { code: "LT", flag: "🇱🇹", name: "Litvanya",        capital: "Vilnius",           lat: 55.2,  lon: 23.9,  region: "europe" },
  { code: "LV", flag: "🇱🇻", name: "Letonya",         capital: "Riga",              lat: 56.9,  lon: 24.6,  region: "europe" },
  { code: "EE", flag: "🇪🇪", name: "Estonya",         capital: "Tallinn",           lat: 58.6,  lon: 25.0,  region: "europe" },
  { code: "FI", flag: "🇫🇮", name: "Finlandiya",      capital: "Helsinki",          lat: 64.0,  lon: 26.0,  region: "europe" },
  { code: "SE", flag: "🇸🇪", name: "İsveç",           capital: "Stockholm",         lat: 62.0,  lon: 15.0,  region: "europe" },
  { code: "NO", flag: "🇳🇴", name: "Norveç",          capital: "Oslo",              lat: 62.0,  lon: 10.0,  region: "europe" },
  { code: "DK", flag: "🇩🇰", name: "Danimarka",       capital: "Kopenhag",          lat: 56.0,  lon: 10.0,  region: "europe" },
  { code: "IS", flag: "🇮🇸", name: "İzlanda",         capital: "Reykjavík",         lat: 65.0,  lon: -18.0, region: "europe" },
  { code: "LU", flag: "🇱🇺", name: "Lüksemburg",      capital: "Lüksemburg",        lat: 49.8,  lon: 6.1,   region: "europe" },
  { code: "MT", flag: "🇲🇹", name: "Malta",           capital: "Valletta",          lat: 35.9,  lon: 14.4,  region: "europe" },
  { code: "CY", flag: "🇨🇾", name: "Kıbrıs",          capital: "Lefkoşa",           lat: 35.1,  lon: 33.4,  region: "europe" },
  { code: "MC", flag: "🇲🇨", name: "Monako",          capital: "Monako",            lat: 43.7,  lon: 7.4,   region: "europe" },
  { code: "LI", flag: "🇱🇮", name: "Lihtenştayn",     capital: "Vaduz",             lat: 47.2,  lon: 9.6,   region: "europe" },
  { code: "AD", flag: "🇦🇩", name: "Andorra",         capital: "Andorra la Vella",  lat: 42.5,  lon: 1.6,   region: "europe" },
  { code: "SM", flag: "🇸🇲", name: "San Marino",      capital: "San Marino",        lat: 43.9,  lon: 12.5,  region: "europe" },
  { code: "VA", flag: "🇻🇦", name: "Vatikan",         capital: "Vatikan Şehri",     lat: 41.9,  lon: 12.5,  region: "europe" },

  // ============================================================
  // ASIA (50)
  // ============================================================
  { code: "JP", flag: "🇯🇵", name: "Japonya",         capital: "Tokyo",             lat: 36.0,  lon: 138.0, region: "asia" },
  { code: "KR", flag: "🇰🇷", name: "Güney Kore",      capital: "Seul",              lat: 37.0,  lon: 127.5, region: "asia" },
  { code: "KP", flag: "🇰🇵", name: "Kuzey Kore",      capital: "Pyongyang",         lat: 40.3,  lon: 127.5, region: "asia" },
  { code: "CN", flag: "🇨🇳", name: "Çin",             capital: "Pekin",             lat: 35.0,  lon: 105.0, region: "asia" },
  { code: "MN", flag: "🇲🇳", name: "Moğolistan",      capital: "Ulan Batur",        lat: 46.9,  lon: 103.8, region: "asia" },
  { code: "IN", flag: "🇮🇳", name: "Hindistan",       capital: "Yeni Delhi",        lat: 22.6,  lon: 79.5,  region: "asia" },
  { code: "PK", flag: "🇵🇰", name: "Pakistan",        capital: "İslamabad",         lat: 30.0,  lon: 70.0,  region: "asia" },
  { code: "BD", flag: "🇧🇩", name: "Bangladeş",       capital: "Dakka",             lat: 23.7,  lon: 90.4,  region: "asia" },
  { code: "LK", flag: "🇱🇰", name: "Sri Lanka",       capital: "Colombo",           lat: 7.9,   lon: 80.8,  region: "asia" },
  { code: "NP", flag: "🇳🇵", name: "Nepal",           capital: "Katmandu",          lat: 28.4,  lon: 84.1,  region: "asia" },
  { code: "BT", flag: "🇧🇹", name: "Bhutan",          capital: "Thimphu",           lat: 27.5,  lon: 90.4,  region: "asia" },
  { code: "MV", flag: "🇲🇻", name: "Maldivler",       capital: "Malé",              lat: 3.2,   lon: 73.2,  region: "asia" },
  { code: "IR", flag: "🇮🇷", name: "İran",            capital: "Tahran",            lat: 32.0,  lon: 53.0,  region: "asia" },
  { code: "IQ", flag: "🇮🇶", name: "Irak",            capital: "Bağdat",            lat: 33.0,  lon: 44.0,  region: "asia" },
  { code: "SY", flag: "🇸🇾", name: "Suriye",          capital: "Şam",               lat: 35.0,  lon: 38.0,  region: "asia" },
  { code: "SA", flag: "🇸🇦", name: "Suudi Arabistan", capital: "Riyad",             lat: 25.0,  lon: 45.0,  region: "asia" },
  { code: "AE", flag: "🇦🇪", name: "BAE",             capital: "Abu Dabi",          lat: 24.0,  lon: 54.0,  region: "asia" },
  { code: "QA", flag: "🇶🇦", name: "Katar",           capital: "Doha",              lat: 25.4,  lon: 51.2,  region: "asia" },
  { code: "KW", flag: "🇰🇼", name: "Kuveyt",          capital: "Kuveyt",            lat: 29.3,  lon: 47.5,  region: "asia" },
  { code: "OM", flag: "🇴🇲", name: "Umman",           capital: "Maskat",            lat: 21.5,  lon: 56.0,  region: "asia" },
  { code: "YE", flag: "🇾🇪", name: "Yemen",           capital: "Sana'a",            lat: 15.6,  lon: 48.5,  region: "asia" },
  { code: "BH", flag: "🇧🇭", name: "Bahreyn",         capital: "Manama",            lat: 25.9,  lon: 50.6,  region: "asia" },
  { code: "IL", flag: "🇮🇱", name: "İsrail",          capital: "Kudüs",             lat: 31.5,  lon: 34.8,  region: "asia" },
  { code: "PS", flag: "🇵🇸", name: "Filistin",        capital: "Ramallah",          lat: 31.9,  lon: 35.2,  region: "asia" },
  { code: "JO", flag: "🇯🇴", name: "Ürdün",           capital: "Amman",             lat: 31.0,  lon: 36.0,  region: "asia" },
  { code: "LB", flag: "🇱🇧", name: "Lübnan",          capital: "Beyrut",            lat: 33.8,  lon: 35.8,  region: "asia" },
  { code: "AZ", flag: "🇦🇿", name: "Azerbaycan",      capital: "Bakü",              lat: 40.5,  lon: 47.5,  region: "asia" },
  { code: "GE", flag: "🇬🇪", name: "Gürcistan",       capital: "Tiflis",            lat: 42.0,  lon: 43.5,  region: "asia" },
  { code: "AM", flag: "🇦🇲", name: "Ermenistan",      capital: "Erivan",            lat: 40.0,  lon: 45.0,  region: "asia" },
  { code: "KZ", flag: "🇰🇿", name: "Kazakistan",      capital: "Astana",            lat: 48.0,  lon: 68.0,  region: "asia" },
  { code: "UZ", flag: "🇺🇿", name: "Özbekistan",      capital: "Taşkent",           lat: 41.0,  lon: 64.0,  region: "asia" },
  { code: "TM", flag: "🇹🇲", name: "Türkmenistan",    capital: "Aşkabat",           lat: 39.0,  lon: 59.6,  region: "asia" },
  { code: "KG", flag: "🇰🇬", name: "Kırgızistan",     capital: "Bişkek",            lat: 41.2,  lon: 74.8,  region: "asia" },
  { code: "TJ", flag: "🇹🇯", name: "Tacikistan",      capital: "Duşanbe",           lat: 38.9,  lon: 71.3,  region: "asia" },
  { code: "AF", flag: "🇦🇫", name: "Afganistan",      capital: "Kabil",             lat: 33.0,  lon: 65.0,  region: "asia" },
  { code: "TH", flag: "🇹🇭", name: "Tayland",         capital: "Bangkok",           lat: 15.0,  lon: 101.0, region: "asia" },
  { code: "VN", flag: "🇻🇳", name: "Vietnam",         capital: "Hanoi",             lat: 16.0,  lon: 106.0, region: "asia" },
  { code: "ID", flag: "🇮🇩", name: "Endonezya",       capital: "Cakarta",           lat: -2.5,  lon: 118.0, region: "asia" },
  { code: "PH", flag: "🇵🇭", name: "Filipinler",      capital: "Manila",            lat: 13.0,  lon: 122.0, region: "asia" },
  { code: "MY", flag: "🇲🇾", name: "Malezya",         capital: "Kuala Lumpur",      lat: 2.5,   lon: 112.5, region: "asia" },
  { code: "SG", flag: "🇸🇬", name: "Singapur",        capital: "Singapur",          lat: 1.3,   lon: 103.8, region: "asia" },
  { code: "BN", flag: "🇧🇳", name: "Brunei",          capital: "Bandar Seri Begawan", lat: 4.5, lon: 114.7, region: "asia" },
  { code: "KH", flag: "🇰🇭", name: "Kamboçya",        capital: "Phnom Penh",        lat: 12.6,  lon: 105.0, region: "asia" },
  { code: "LA", flag: "🇱🇦", name: "Laos",            capital: "Vientiane",         lat: 19.9,  lon: 102.5, region: "asia" },
  { code: "MM", flag: "🇲🇲", name: "Myanmar",         capital: "Naypyidaw",         lat: 21.9,  lon: 96.0,  region: "asia" },
  { code: "TL", flag: "🇹🇱", name: "Doğu Timor",      capital: "Dili",              lat: -8.9,  lon: 125.7, region: "asia" },

  // ============================================================
  // AFRICA (54)
  // ============================================================
  { code: "EG", flag: "🇪🇬", name: "Mısır",           capital: "Kahire",            lat: 27.0,  lon: 30.0,  region: "africa" },
  { code: "LY", flag: "🇱🇾", name: "Libya",           capital: "Trablus",           lat: 25.0,  lon: 17.0,  region: "africa" },
  { code: "TN", flag: "🇹🇳", name: "Tunus",           capital: "Tunus",             lat: 34.0,  lon: 9.0,   region: "africa" },
  { code: "DZ", flag: "🇩🇿", name: "Cezayir",         capital: "Cezayir",           lat: 28.0,  lon: 3.0,   region: "africa" },
  { code: "MA", flag: "🇲🇦", name: "Fas",             capital: "Rabat",             lat: 32.0,  lon: -5.0,  region: "africa" },
  { code: "SD", flag: "🇸🇩", name: "Sudan",           capital: "Hartum",            lat: 13.0,  lon: 30.0,  region: "africa" },
  { code: "SS", flag: "🇸🇸", name: "Güney Sudan",     capital: "Cuba",              lat: 7.9,   lon: 31.3,  region: "africa" },
  { code: "ZA", flag: "🇿🇦", name: "Güney Afrika",    capital: "Pretoria",          lat: -29.0, lon: 24.0,  region: "africa" },
  { code: "NG", flag: "🇳🇬", name: "Nijerya",         capital: "Abuja",             lat: 10.0,  lon: 8.0,   region: "africa" },
  { code: "KE", flag: "🇰🇪", name: "Kenya",           capital: "Nairobi",           lat: 1.0,   lon: 38.0,  region: "africa" },
  { code: "ET", flag: "🇪🇹", name: "Etiyopya",        capital: "Addis Ababa",       lat: 8.0,   lon: 38.0,  region: "africa" },
  { code: "SN", flag: "🇸🇳", name: "Senegal",         capital: "Dakar",             lat: 14.0,  lon: -14.0, region: "africa" },
  { code: "GH", flag: "🇬🇭", name: "Gana",            capital: "Accra",             lat: 8.0,   lon: -2.0,  region: "africa" },
  { code: "MZ", flag: "🇲🇿", name: "Mozambik",        capital: "Maputo",            lat: -18.7, lon: 35.5,  region: "africa" },
  { code: "TZ", flag: "🇹🇿", name: "Tanzanya",        capital: "Dodoma",            lat: -6.4,  lon: 34.9,  region: "africa" },
  { code: "UG", flag: "🇺🇬", name: "Uganda",          capital: "Kampala",           lat: 1.4,   lon: 32.3,  region: "africa" },
  { code: "CM", flag: "🇨🇲", name: "Kamerun",         capital: "Yaoundé",           lat: 7.4,   lon: 12.4,  region: "africa" },
  { code: "CI", flag: "🇨🇮", name: "Fildişi Sahili",  capital: "Yamoussoukro",      lat: 7.5,   lon: -5.5,  region: "africa" },
  { code: "ML", flag: "🇲🇱", name: "Mali",            capital: "Bamako",            lat: 17.6,  lon: -4.0,  region: "africa" },
  { code: "NE", flag: "🇳🇪", name: "Nijer",           capital: "Niamey",            lat: 17.6,  lon: 8.1,   region: "africa" },
  { code: "BF", flag: "🇧🇫", name: "Burkina Faso",    capital: "Ouagadougou",       lat: 12.2,  lon: -1.6,  region: "africa" },
  { code: "MG", flag: "🇲🇬", name: "Madagaskar",      capital: "Antananarivo",      lat: -18.8, lon: 46.9,  region: "africa" },
  { code: "AO", flag: "🇦🇴", name: "Angola",          capital: "Luanda",            lat: -11.2, lon: 17.9,  region: "africa" },
  { code: "ZM", flag: "🇿🇲", name: "Zambiya",         capital: "Lusaka",            lat: -13.1, lon: 27.8,  region: "africa" },
  { code: "ZW", flag: "🇿🇼", name: "Zimbabve",        capital: "Harare",            lat: -19.0, lon: 29.2,  region: "africa" },
  { code: "BW", flag: "🇧🇼", name: "Botsvana",        capital: "Gaborone",          lat: -22.3, lon: 24.7,  region: "africa" },
  { code: "NA", flag: "🇳🇦", name: "Namibya",         capital: "Windhoek",          lat: -23.0, lon: 18.5,  region: "africa" },
  { code: "MR", flag: "🇲🇷", name: "Moritanya",       capital: "Nouakchott",        lat: 21.0,  lon: -11.0, region: "africa" },
  { code: "SO", flag: "🇸🇴", name: "Somali",          capital: "Mogadişu",          lat: 5.2,   lon: 46.2,  region: "africa" },
  { code: "ER", flag: "🇪🇷", name: "Eritre",          capital: "Asmara",            lat: 15.2,  lon: 39.8,  region: "africa" },
  { code: "DJ", flag: "🇩🇯", name: "Cibuti",          capital: "Cibuti",            lat: 11.8,  lon: 42.6,  region: "africa" },
  { code: "RW", flag: "🇷🇼", name: "Ruanda",          capital: "Kigali",            lat: -1.9,  lon: 29.9,  region: "africa" },
  { code: "BI", flag: "🇧🇮", name: "Burundi",         capital: "Gitega",            lat: -3.4,  lon: 29.9,  region: "africa" },
  { code: "CF", flag: "🇨🇫", name: "Orta Afrika",     capital: "Bangui",            lat: 6.6,   lon: 20.9,  region: "africa" },
  { code: "TD", flag: "🇹🇩", name: "Çad",             capital: "N'Djamena",         lat: 15.5,  lon: 18.7,  region: "africa" },
  { code: "GA", flag: "🇬🇦", name: "Gabon",           capital: "Libreville",        lat: -0.8,  lon: 11.6,  region: "africa" },
  { code: "CG", flag: "🇨🇬", name: "Kongo Cumhuriyeti", capital: "Brazzaville",     lat: -0.2,  lon: 15.8,  region: "africa" },
  { code: "CD", flag: "🇨🇩", name: "DR Kongo",        capital: "Kinşasa",           lat: -4.0,  lon: 21.8,  region: "africa" },
  { code: "LR", flag: "🇱🇷", name: "Liberya",         capital: "Monrovia",          lat: 6.4,   lon: -9.4,  region: "africa" },
  { code: "SL", flag: "🇸🇱", name: "Sierra Leone",    capital: "Freetown",          lat: 8.5,   lon: -11.8, region: "africa" },
  { code: "GN", flag: "🇬🇳", name: "Gine",            capital: "Konakri",           lat: 9.9,   lon: -9.7,  region: "africa" },
  { code: "GW", flag: "🇬🇼", name: "Gine-Bissau",     capital: "Bissau",            lat: 11.8,  lon: -15.2, region: "africa" },
  { code: "TG", flag: "🇹🇬", name: "Togo",            capital: "Lomé",              lat: 8.6,   lon: 0.8,   region: "africa" },
  { code: "BJ", flag: "🇧🇯", name: "Benin",           capital: "Porto-Novo",        lat: 9.3,   lon: 2.3,   region: "africa" },
  { code: "MW", flag: "🇲🇼", name: "Malavi",          capital: "Lilongwe",          lat: -13.3, lon: 34.3,  region: "africa" },
  { code: "LS", flag: "🇱🇸", name: "Lesotho",         capital: "Maseru",            lat: -29.6, lon: 28.2,  region: "africa" },
  { code: "SZ", flag: "🇸🇿", name: "Esvatini",        capital: "Mbabane",           lat: -26.5, lon: 31.5,  region: "africa" },
  { code: "MU", flag: "🇲🇺", name: "Mauritius",       capital: "Port Louis",        lat: -20.3, lon: 57.5,  region: "africa" },
  { code: "CV", flag: "🇨🇻", name: "Yeşil Burun",     capital: "Praia",             lat: 16.5,  lon: -23.5, region: "africa" },
  { code: "GQ", flag: "🇬🇶", name: "Ekvator Ginesi",  capital: "Malabo",            lat: 1.7,   lon: 10.3,  region: "africa" },
  { code: "GM", flag: "🇬🇲", name: "Gambiya",         capital: "Banjul",            lat: 13.4,  lon: -15.5, region: "africa" },
  { code: "KM", flag: "🇰🇲", name: "Komorlar",        capital: "Moroni",            lat: -11.9, lon: 43.9,  region: "africa" },
  { code: "ST", flag: "🇸🇹", name: "São Tomé",        capital: "São Tomé",          lat: 0.2,   lon: 6.6,   region: "africa" },
  { code: "SC", flag: "🇸🇨", name: "Seyşeller",       capital: "Victoria",          lat: -4.7,  lon: 55.5,  region: "africa" },

  // ============================================================
  // AMERICA (35)
  // ============================================================
  { code: "US", flag: "🇺🇸", name: "ABD",             capital: "Washington",        lat: 38.0,  lon: -97.0, region: "america" },
  { code: "CA", flag: "🇨🇦", name: "Kanada",          capital: "Ottawa",            lat: 62.4,  lon: -96.8, region: "america" },
  { code: "MX", flag: "🇲🇽", name: "Meksika",         capital: "Meksiko",           lat: 23.0,  lon: -102.0,region: "america" },
  { code: "BR", flag: "🇧🇷", name: "Brezilya",        capital: "Brasilia",          lat: -10.0, lon: -55.0, region: "america" },
  { code: "AR", flag: "🇦🇷", name: "Arjantin",        capital: "Buenos Aires",      lat: -38.4, lon: -63.6, region: "america" },
  { code: "CL", flag: "🇨🇱", name: "Şili",            capital: "Santiago",          lat: -30.0, lon: -71.0, region: "america" },
  { code: "PE", flag: "🇵🇪", name: "Peru",            capital: "Lima",              lat: -10.0, lon: -76.0, region: "america" },
  { code: "CO", flag: "🇨🇴", name: "Kolombiya",       capital: "Bogotá",            lat: 4.0,   lon: -72.0, region: "america" },
  { code: "VE", flag: "🇻🇪", name: "Venezuela",       capital: "Karakas",           lat: 8.0,   lon: -66.0, region: "america" },
  { code: "CU", flag: "🇨🇺", name: "Küba",            capital: "Havana",            lat: 22.0,  lon: -79.5, region: "america" },
  { code: "BO", flag: "🇧🇴", name: "Bolivya",         capital: "Sucre",             lat: -16.3, lon: -63.6, region: "america" },
  { code: "EC", flag: "🇪🇨", name: "Ekvador",         capital: "Quito",             lat: -1.8,  lon: -78.2, region: "america" },
  { code: "PY", flag: "🇵🇾", name: "Paraguay",        capital: "Asunción",          lat: -23.4, lon: -58.4, region: "america" },
  { code: "UY", flag: "🇺🇾", name: "Uruguay",         capital: "Montevideo",        lat: -32.5, lon: -55.8, region: "america" },
  { code: "GY", flag: "🇬🇾", name: "Guyana",          capital: "Georgetown",        lat: 4.9,   lon: -58.9, region: "america" },
  { code: "SR", flag: "🇸🇷", name: "Surinam",         capital: "Paramaribo",        lat: 3.9,   lon: -56.0, region: "america" },
  { code: "PA", flag: "🇵🇦", name: "Panama",          capital: "Panama",            lat: 8.5,   lon: -80.8, region: "america" },
  { code: "CR", flag: "🇨🇷", name: "Kosta Rika",      capital: "San José",          lat: 9.7,   lon: -83.8, region: "america" },
  { code: "NI", flag: "🇳🇮", name: "Nikaragua",       capital: "Managua",           lat: 12.9,  lon: -85.2, region: "america" },
  { code: "HN", flag: "🇭🇳", name: "Honduras",        capital: "Tegucigalpa",       lat: 15.2,  lon: -86.2, region: "america" },
  { code: "SV", flag: "🇸🇻", name: "El Salvador",     capital: "San Salvador",      lat: 13.8,  lon: -88.9, region: "america" },
  { code: "GT", flag: "🇬🇹", name: "Guatemala",       capital: "Guatemala",         lat: 15.8,  lon: -90.2, region: "america" },
  { code: "BZ", flag: "🇧🇿", name: "Belize",          capital: "Belmopan",          lat: 17.2,  lon: -88.5, region: "america" },
  { code: "DO", flag: "🇩🇴", name: "Dominik Cum.",    capital: "Santo Domingo",     lat: 18.7,  lon: -70.2, region: "america" },
  { code: "HT", flag: "🇭🇹", name: "Haiti",           capital: "Port-au-Prince",    lat: 19.0,  lon: -72.3, region: "america" },
  { code: "JM", flag: "🇯🇲", name: "Jamaika",         capital: "Kingston",          lat: 18.1,  lon: -77.3, region: "america" },
  { code: "BS", flag: "🇧🇸", name: "Bahamalar",       capital: "Nassau",            lat: 25.0,  lon: -77.4, region: "america" },
  { code: "TT", flag: "🇹🇹", name: "Trinidad ve Tobago", capital: "Port of Spain",  lat: 10.7,  lon: -61.2, region: "america" },
  { code: "BB", flag: "🇧🇧", name: "Barbados",        capital: "Bridgetown",        lat: 13.2,  lon: -59.5, region: "america" },
  { code: "GD", flag: "🇬🇩", name: "Grenada",         capital: "Saint George's",    lat: 12.1,  lon: -61.7, region: "america" },
  { code: "LC", flag: "🇱🇨", name: "Saint Lucia",     capital: "Castries",          lat: 13.9,  lon: -60.9, region: "america" },
  { code: "AG", flag: "🇦🇬", name: "Antigua ve Barbuda", capital: "Saint John's",   lat: 17.1,  lon: -61.8, region: "america" },
  { code: "DM", flag: "🇩🇲", name: "Dominika",        capital: "Roseau",            lat: 15.4,  lon: -61.4, region: "america" },
  { code: "KN", flag: "🇰🇳", name: "Saint Kitts ve Nevis", capital: "Basseterre",   lat: 17.3,  lon: -62.7, region: "america" },
  { code: "VC", flag: "🇻🇨", name: "Saint Vincent",   capital: "Kingstown",         lat: 13.3,  lon: -61.2, region: "america" },

  // ============================================================
  // OCEANIA (12)
  // ============================================================
  { code: "AU", flag: "🇦🇺", name: "Avustralya",      capital: "Canberra",          lat: -27.0, lon: 133.0, region: "oceania" },
  { code: "NZ", flag: "🇳🇿", name: "Yeni Zelanda",    capital: "Wellington",        lat: -41.0, lon: 174.0, region: "oceania" },
  { code: "PG", flag: "🇵🇬", name: "Papua Yeni Gine", capital: "Port Moresby",      lat: -6.3,  lon: 144.0, region: "oceania" },
  { code: "FJ", flag: "🇫🇯", name: "Fiji",            capital: "Suva",              lat: -17.7, lon: 178.1, region: "oceania" },
  { code: "SB", flag: "🇸🇧", name: "Solomon Adaları", capital: "Honiara",           lat: -9.6,  lon: 160.2, region: "oceania" },
  { code: "VU", flag: "🇻🇺", name: "Vanuatu",         capital: "Port Vila",         lat: -15.4, lon: 167.0, region: "oceania" },
  { code: "WS", flag: "🇼🇸", name: "Samoa",           capital: "Apia",              lat: -13.8, lon: -172.1, region: "oceania" },
  { code: "TO", flag: "🇹🇴", name: "Tonga",           capital: "Nuku'alofa",        lat: -21.2, lon: -175.2, region: "oceania" },
  { code: "KI", flag: "🇰🇮", name: "Kiribati",        capital: "Tarawa",            lat: 1.5,   lon: 173.0, region: "oceania" },
  { code: "FM", flag: "🇫🇲", name: "Mikronezya",      capital: "Palikir",           lat: 6.9,   lon: 158.2, region: "oceania" },
  { code: "MH", flag: "🇲🇭", name: "Marshall Adaları", capital: "Majuro",           lat: 7.1,   lon: 171.4, region: "oceania" },
  { code: "PW", flag: "🇵🇼", name: "Palau",           capital: "Ngerulmud",         lat: 7.5,   lon: 134.6, region: "oceania" }
];
