/* Emoji Quiz - question pool (curated)
 * To add questions, append to QUESTIONS. Each entry has:
 *   emojis    : the emoji clue (string)
 *   answer    : correct answer (Turkish)
 *   category  : category id (see CATEGORY_LABELS in script.js)
 *
 * Categories: yemek, sehir, deyim, film, dunya, hayvan, spor,
 *             meslek, doga, arac, esya, muzik, okul
 */
window.QUESTIONS = [
  // ============================================================
  // YEMEK (Food) — sadece çok-emojili / az tanıdık olanlar
  // ============================================================
  { emojis: "🥩🍢",    answer: "Şiş Kebap",          category: "yemek" },
  { emojis: "🍯🌰",    answer: "Baklava",            category: "yemek" },
  { emojis: "☕🇹🇷",   answer: "Türk Kahvesi",       category: "yemek" },
  { emojis: "🍆🍅🥩",  answer: "Karnıyarık",         category: "yemek" },
  { emojis: "🥩🍞🌯",  answer: "Döner",              category: "yemek" },
  { emojis: "🥟🥩",    answer: "Mantı",              category: "yemek" },
  { emojis: "🍅🥒🍞🧅", answer: "Menemen",            category: "yemek" },
  { emojis: "🥛🍚🍮",  answer: "Sütlaç",             category: "yemek" },
  { emojis: "🐑🍚",    answer: "Pilav",              category: "yemek" },
  { emojis: "🌿🍵🇹🇷", answer: "Türk Çayı",          category: "yemek" },
  { emojis: "🥖🇫🇷",   answer: "Fransız Bageti",     category: "yemek" },
  { emojis: "🌽🍿🎬",  answer: "Sinema Mısırı",      category: "yemek" },
  { emojis: "🥯🇹🇷",   answer: "Simit",              category: "yemek" },
  { emojis: "🥚🍳🌅", answer: "Kahvaltı",            category: "yemek" },
  { emojis: "🎂🕯️🎉", answer: "Doğum Günü Pastası", category: "yemek" },
  { emojis: "🥧🍎",    answer: "Elmalı Turta",       category: "yemek" },
  { emojis: "🍪🥛",    answer: "Kurabiye ve Süt",    category: "yemek" },
  { emojis: "🍩🍫",    answer: "Çikolatalı Donut",   category: "yemek" },
  { emojis: "🍓🍰",    answer: "Çilekli Pasta",      category: "yemek" },
  { emojis: "🍫🥛",    answer: "Sıcak Çikolata",     category: "yemek" },
  { emojis: "🍋🍯🥤",  answer: "Limonata",           category: "yemek" },
  { emojis: "🍇🍷",    answer: "Şarap",              category: "yemek" },
  { emojis: "🥥🌴",    answer: "Hindistan Cevizi",   category: "yemek" },
  { emojis: "🍅🧀🌿",  answer: "Margarita Pizza",    category: "yemek" },
  { emojis: "🐟🍚🇯🇵", answer: "Suşi",               category: "yemek" },
  { emojis: "🌯🌶️🥩", answer: "Acılı Dürüm",        category: "yemek" },
  { emojis: "🥕🥬🍲",  answer: "Sebze Çorbası",      category: "yemek" },
  { emojis: "🍞🧀🇮🇹", answer: "Tost",               category: "yemek" },
  { emojis: "🐔🍚🥕",  answer: "Tavuklu Pilav",      category: "yemek" },
  { emojis: "🥩🍞🥗🍟", answer: "Hamburger Menüsü",  category: "yemek" },

  // ============================================================
  // ŞEHİR (City) — emoji-kombo
  // ============================================================
  { emojis: "🌉🕌",      answer: "İstanbul",   category: "sehir" },
  { emojis: "🎈🪨",      answer: "Kapadokya",  category: "sehir" },
  { emojis: "⛵🌊",      answer: "Bodrum",     category: "sehir" },
  { emojis: "🛁💧🤍",   answer: "Pamukkale",  category: "sehir" },
  { emojis: "🏛️🇹🇷",   answer: "Ankara",     category: "sehir" },
  { emojis: "☀️🏝️🇹🇷",answer: "Antalya",    category: "sehir" },
  { emojis: "🚢⛴️🇹🇷", answer: "İzmir",      category: "sehir" },
  { emojis: "🌶️🥙",    answer: "Adana",      category: "sehir" },
  { emojis: "🌋🎿",     answer: "Erciyes",    category: "sehir" },
  { emojis: "🎓🏫🇹🇷", answer: "Eskişehir",  category: "sehir" },
  { emojis: "🌹🇹🇷",   answer: "Isparta",    category: "sehir" },
  { emojis: "🍇🇹🇷",   answer: "Manisa",     category: "sehir" },
  { emojis: "🐟🌊🇹🇷", answer: "Trabzon",    category: "sehir" },
  { emojis: "🌳🐻🇹🇷", answer: "Bolu",       category: "sehir" },
  { emojis: "🍒🇹🇷",   answer: "Tekirdağ",   category: "sehir" },
  { emojis: "🐢🇹🇷",   answer: "Çanakkale",  category: "sehir" },
  { emojis: "🌸🇹🇷",   answer: "Yalova",     category: "sehir" },
  { emojis: "🥖🇹🇷",   answer: "Edirne",     category: "sehir" },
  { emojis: "⛪🇹🇷",   answer: "Mardin",     category: "sehir" },
  { emojis: "🍑🌳🇹🇷", answer: "Bursa",      category: "sehir" },
  { emojis: "🍇🍷🇹🇷", answer: "Şarköy",     category: "sehir" },
  { emojis: "🌶️🍅🇹🇷",answer: "Şanlıurfa",  category: "sehir" },
  { emojis: "🌊🐬🇹🇷", answer: "Marmaris",   category: "sehir" },
  { emojis: "🗼🇫🇷",   answer: "Paris",      category: "sehir" },
  { emojis: "🗽🌉🇺🇸", answer: "New York",   category: "sehir" },
  { emojis: "🐼🇨🇳",   answer: "Pekin",      category: "sehir" },
  { emojis: "🍕🛕🇮🇹", answer: "Roma",       category: "sehir" },
  { emojis: "⚽🇪🇸",   answer: "Madrid",     category: "sehir" },
  { emojis: "🎰🌃",    answer: "Las Vegas",  category: "sehir" },
  { emojis: "🎬⭐🌴",  answer: "Hollywood",  category: "sehir" },
  { emojis: "🏰🇬🇧",   answer: "Londra",     category: "sehir" },
  { emojis: "⛩️🥋🇯🇵", answer: "Tokyo",      category: "sehir" },
  { emojis: "🍻🥨🇩🇪", answer: "Münih",      category: "sehir" },
  { emojis: "🐫🏜️🇦🇪", answer: "Dubai",     category: "sehir" },
  { emojis: "🌊🛶🇮🇹", answer: "Venedik",    category: "sehir" },
  { emojis: "🛕🇮🇳",   answer: "Delhi",      category: "sehir" },
  { emojis: "🦅🏛️🇺🇸",answer: "Washington", category: "sehir" },
  { emojis: "🏖️🌴🇧🇷", answer: "Rio",        category: "sehir" },
  { emojis: "🍷🎭🇮🇹", answer: "Floransa",   category: "sehir" },
  { emojis: "🍻🌭🇨🇿", answer: "Prag",       category: "sehir" },

  // ============================================================
  // ATASÖZÜ / DEYİM (curated)
  // ============================================================
  { emojis: "💧💧🌊",  answer: "Damlaya damlaya göl olur",          category: "deyim" },
  { emojis: "🪨🐦🐦", answer: "Bir taşla iki kuş",                  category: "deyim" },
  { emojis: "🤐🥇",   answer: "Sükut altındır",                     category: "deyim" },
  { emojis: "🌳🍎😋", answer: "Armut piş ağzıma düş",               category: "deyim" },
  { emojis: "🐺☁️🐺", answer: "Kurtla yatan kurtla kalkar",         category: "deyim" },
  { emojis: "🏃💨🐢", answer: "Acele işe şeytan karışır",           category: "deyim" },
  { emojis: "☀️🌧️🤝",answer: "Dost kara günde belli olur",         category: "deyim" },
  { emojis: "🍇👀🍇", answer: "Üzüm üzüme baka baka kararır",       category: "deyim" },
  { emojis: "🌱➡️🌾", answer: "Ne ekersen onu biçersin",           category: "deyim" },
  { emojis: "🌾📦⏰", answer: "Sakla samanı gelir zamanı",          category: "deyim" },
  { emojis: "🍯👆👅", answer: "Bal tutan parmağını yalar",          category: "deyim" },
  { emojis: "🐔😴🌾", answer: "Aç tavuk düşünde darı görür",        category: "deyim" },
  { emojis: "👅➡️🤕", answer: "Dilden çıkan başa gelir",            category: "deyim" },
  { emojis: "🍯💬🐍", answer: "Tatlı dil yılanı deliğinden çıkarır",category: "deyim" },
  { emojis: "👁️❌💔",answer: "Gözden ırak olan gönülden de ırak olur",category: "deyim" },
  { emojis: "🕯️⬇️❌",answer: "Mum dibine ışık vermez",             category: "deyim" },
  { emojis: "🛏️📏👣",answer: "Ayağını yorganına göre uzat",        category: "deyim" },
  { emojis: "👤👤💪", answer: "Birlikten kuvvet doğar",             category: "deyim" },
  { emojis: "⏰💰",   answer: "Vakit nakittir",                     category: "deyim" },
  { emojis: "🐦🐦🪺", answer: "Yuvayı dişi kuş yapar",              category: "deyim" },
  { emojis: "🧠➡️🗣️",answer: "Önce düşün sonra konuş",             category: "deyim" },
  { emojis: "🧘🎯",   answer: "Sabreden derviş muradına ermiş",     category: "deyim" },
  { emojis: "🌳🍎⬇️", answer: "Armut dibine düşer",                 category: "deyim" },
  { emojis: "📖🧠",   answer: "Kitap insanın en iyi dostudur",      category: "deyim" },
  { emojis: "🤝💪",   answer: "El elden üstündür",                  category: "deyim" },
  { emojis: "💧🪨⏰", answer: "Damla damla taşı deler",              category: "deyim" },
  { emojis: "🐺🐑👕", answer: "Kuzu postuna bürünmüş kurt",         category: "deyim" },
  { emojis: "🐎🚪💨", answer: "Atı alan Üsküdar'ı geçti",           category: "deyim" },
  { emojis: "🐔🥚❓", answer: "Tavuk mu yumurtadan, yumurta mı tavuktan", category: "deyim" },
  { emojis: "🔥➕🔥", answer: "Ateşle oynamak",                     category: "deyim" },

  // ============================================================
  // FİLM / DİZİ — emoji-kombo
  // ============================================================
  { emojis: "👨‍👦💔",   answer: "Babam ve Oğlum",     category: "film" },
  { emojis: "🚀👽😂",   answer: "G.O.R.A.",           category: "film" },
  { emojis: "💪😂🇹🇷", answer: "Recep İvedik",       category: "film" },
  { emojis: "🌹🍂💔",   answer: "Yaprak Dökümü",      category: "film" },
  { emojis: "🌹🍷❤️",   answer: "Aşk-ı Memnu",        category: "film" },
  { emojis: "🐺🇹🇷👮", answer: "Kurtlar Vadisi",     category: "film" },
  { emojis: "🏰👑📜",   answer: "Muhteşem Yüzyıl",    category: "film" },
  { emojis: "🥋👴🇹🇷", answer: "Karadayı",           category: "film" },
  { emojis: "🦁👑🌅",   answer: "Aslan Kral",         category: "film" },
  { emojis: "🐭🧀🏃",   answer: "Tom ve Jerry",       category: "film" },
  { emojis: "🦇🌃🦸",   answer: "Batman",             category: "film" },
  { emojis: "🕷️👨🕸️", answer: "Örümcek Adam",       category: "film" },
  { emojis: "⚔️🌌🚀",  answer: "Yıldız Savaşları",   category: "film" },
  { emojis: "🐠🌊🔍",  answer: "Kayıp Balık Nemo",   category: "film" },
  { emojis: "🍎🐍🌳",  answer: "Adem ile Havva",     category: "film" },
  { emojis: "🏠🐺🐷🐷🐷", answer: "Üç Küçük Domuz",  category: "film" },
  { emojis: "❄️👸⛄",  answer: "Karlar Ülkesi",      category: "film" },
  { emojis: "👸🐸🤴",  answer: "Prenses ve Kurbağa", category: "film" },
  { emojis: "🏰🌹👹",  answer: "Güzel ve Çirkin",    category: "film" },
  { emojis: "🐟😱🌊",  answer: "Köpek Balığı (Jaws)",category: "film" },
  { emojis: "🦖🦕🏝️", answer: "Jurassic Park",     category: "film" },
  { emojis: "💍🌋👤",  answer: "Yüzüklerin Efendisi",category: "film" },
  { emojis: "⚡🧙‍♂️🏰",answer: "Harry Potter",       category: "film" },
  { emojis: "🤖🚀⚙️", answer: "Transformers",       category: "film" },
  { emojis: "🚢❄️💔",  answer: "Titanic",            category: "film" },
  { emojis: "👽🚲🌕",  answer: "E.T.",               category: "film" },
  { emojis: "🎭🃏🟣", answer: "Joker",              category: "film" },
  { emojis: "🦸🦸🦸", answer: "Yenilmezler",        category: "film" },
  { emojis: "🕶️💊🟢",answer: "Matrix",             category: "film" },
  { emojis: "🦍🍌🏙️",answer: "King Kong",          category: "film" },
  { emojis: "🐙🌊⚓", answer: "Karayip Korsanları", category: "film" },
  { emojis: "🍄🍄👑", answer: "Süper Mario",        category: "film" },
  { emojis: "🐝🐝🍯", answer: "Arı Maya",           category: "film" },
  { emojis: "🐭👨‍🍳", answer: "Ratatuy",            category: "film" },
  { emojis: "🚗💨🏁", answer: "Hızlı ve Öfkeli",    category: "film" },
  { emojis: "🚀🌌👨‍🚀",answer: "Yıldızlararası",    category: "film" },
  { emojis: "🤖❤️🌍", answer: "Wall-E",             category: "film" },
  { emojis: "👻👻🏚️", answer: "Hayalet Avcıları",   category: "film" },
  { emojis: "🇹🇷⚽😢", answer: "Cüneyt Arkın",      category: "film" },
  { emojis: "🚌🇹🇷😂", answer: "Yahşi Batı",        category: "film" },
  { emojis: "🎤🎵😂🏚️",answer: "Vizontele",        category: "film" },
  { emojis: "🚗💨🐶", answer: "Kınalı Hanzo",       category: "film" },
  { emojis: "🚓👮💪", answer: "Polis Akademisi",    category: "film" },
  { emojis: "👰👨‍🦰💔",answer: "Düğün Dernek",      category: "film" },
  { emojis: "🏫👨‍🎓🇹🇷",answer: "Hababam Sınıfı",   category: "film" },
  { emojis: "🐺🚓🔍", answer: "Behzat Ç.",          category: "film" },
  { emojis: "👰❤️🧑‍🦱",answer: "Sen Çal Kapımı",    category: "film" },
  { emojis: "🌹🏠❤️", answer: "Erkenci Kuş",        category: "film" },
  { emojis: "🏠💍❤️", answer: "Kara Sevda",         category: "film" },
  { emojis: "👮‍♀️🔍🕳️",answer: "Çukur",            category: "film" },
  { emojis: "🚪👤🗝️", answer: "Diriliş Ertuğrul",  category: "film" },
  { emojis: "⚔️👑🌳", answer: "Kuruluş Osman",      category: "film" },
  { emojis: "🏝️🥥🛶", answer: "Robinson Crusoe",   category: "film" },
  { emojis: "👨‍🚀🌑🚀",answer: "Ay'a Yolculuk",    category: "film" },
  { emojis: "🦏🐘🦁🌍",answer: "Madagaskar",       category: "film" },
  { emojis: "🦎🦷🐍😈",answer: "Game of Thrones",   category: "film" },
  { emojis: "🟦🟦💊",  answer: "Breaking Bad",      category: "film" },
  { emojis: "🦑🟢🟥", answer: "Squid Game",         category: "film" },
  { emojis: "🌶️📋🎬", answer: "Çağan Irmak Filmi", category: "film" },

  // ============================================================
  // DÜNYA / GENEL — emoji-kombo
  // ============================================================
  { emojis: "🌍🌎🌏",   answer: "Dünya",                 category: "dunya" },
  { emojis: "🎄🎁🎅",   answer: "Yılbaşı",               category: "dunya" },
  { emojis: "💍👰🤵",   answer: "Düğün",                 category: "dunya" },
  { emojis: "🌹❤️💕",   answer: "Sevgililer Günü",       category: "dunya" },
  { emojis: "🎆🎇🌃",   answer: "Havai Fişek",           category: "dunya" },
  { emojis: "🏆🥇🎖️",   answer: "Şampiyonluk",           category: "dunya" },
  { emojis: "📚🎓👨‍🎓", answer: "Mezuniyet",             category: "dunya" },
  { emojis: "🎤🎸🎵",   answer: "Konser",                category: "dunya" },
  { emojis: "🎬🎥🍿",   answer: "Sinema",                category: "dunya" },
  { emojis: "💰💵💴",   answer: "Para",                  category: "dunya" },
  { emojis: "🏦🏧💳",   answer: "Banka",                 category: "dunya" },
  { emojis: "🛒🛍️",    answer: "Alışveriş",             category: "dunya" },
  { emojis: "🏥💊💉",   answer: "Hastane",               category: "dunya" },
  { emojis: "🚓🚨👮",   answer: "Polis",                 category: "dunya" },
  { emojis: "🚒🔥👨‍🚒", answer: "İtfaiye",               category: "dunya" },
  { emojis: "✈️🛫🌍",  answer: "Tatil",                 category: "dunya" },
  { emojis: "🏨🛏️🔑",  answer: "Otel",                  category: "dunya" },
  { emojis: "🏖️🌴☀️",  answer: "Plaj",                  category: "dunya" },
  { emojis: "⛷️🎿❄️",  answer: "Kayak",                 category: "dunya" },
  { emojis: "🎢🎡🎠",  answer: "Lunapark",              category: "dunya" },
  { emojis: "🌋🔥💨",  answer: "Volkan",                category: "dunya" },
  { emojis: "🏞️🏔️🌲",answer: "Doğa",                  category: "dunya" },
  { emojis: "🧙‍♂️🪄✨",answer: "Sihir",                 category: "dunya" },
  { emojis: "👻🎃🦇", answer: "Cadılar Bayramı",       category: "dunya" },
  { emojis: "🌈☔🌧️", answer: "Gökkuşağı",             category: "dunya" },
  { emojis: "🎪🎭🤹", answer: "Sirk",                  category: "dunya" },
  { emojis: "💎💰👑", answer: "Hazine",                category: "dunya" },
  { emojis: "🗺️🧭⛰️",answer: "Macera",               category: "dunya" },
  { emojis: "✉️📮📬", answer: "Mektup",               category: "dunya" },
  { emojis: "🔑🚪🏠", answer: "Eve Geliş",             category: "dunya" },
  { emojis: "🛁🚿💧", answer: "Banyo",                category: "dunya" },
  { emojis: "🧹🪣🧽", answer: "Temizlik",             category: "dunya" },
  { emojis: "🛏️😴💤", answer: "Uyku",                 category: "dunya" },
  { emojis: "📅📆🗓️", answer: "Takvim",               category: "dunya" },
  { emojis: "🚇🚆🚂", answer: "Tren",                 category: "dunya" },
  { emojis: "🛸👽🌌", answer: "UFO",                  category: "dunya" },
  { emojis: "🌙🌟💤", answer: "Gece",                  category: "dunya" },
  { emojis: "☀️🌤️🌅", answer: "Sabah",                category: "dunya" },
  { emojis: "🥶❄️🧣", answer: "Kış",                   category: "dunya" },
  { emojis: "🌷🌸🐝", answer: "İlkbahar",              category: "dunya" },
  { emojis: "🍂🍁🎃", answer: "Sonbahar",              category: "dunya" },
  { emojis: "☀️🍉🩴", answer: "Yaz",                   category: "dunya" },
  { emojis: "🇹🇷🌙⭐", answer: "Türk Bayrağı",         category: "dunya" },
  { emojis: "📿🕌🌙", answer: "Ramazan",              category: "dunya" },
  { emojis: "🐑👴🕌", answer: "Kurban Bayramı",       category: "dunya" },

  // ============================================================
  // HAYVAN — sadece az tanıdık + multi-emoji
  // ============================================================
  { emojis: "🐺🌕🌲",  answer: "Kurt",          category: "hayvan" },
  { emojis: "🦊🐔🐔", answer: "Tilki",         category: "hayvan" },
  { emojis: "🐢💨🐇", answer: "Tavşan ve Kaplumbağa", category: "hayvan" },
  { emojis: "🦛💧",    answer: "Su Aygırı",     category: "hayvan" },
  { emojis: "🦘🇦🇺",  answer: "Kanguru",       category: "hayvan" },
  { emojis: "🦒🌳",    answer: "Zürafa",        category: "hayvan" },
  { emojis: "🦏🌵",    answer: "Gergedan",      category: "hayvan" },
  { emojis: "🦅🏔️",   answer: "Kartal",        category: "hayvan" },
  { emojis: "🦉🌙🌲", answer: "Baykuş",        category: "hayvan" },
  { emojis: "🦜🌴🏴‍☠️",answer: "Papağan",      category: "hayvan" },
  { emojis: "🐧❄️🐟", answer: "Penguen",       category: "hayvan" },
  { emojis: "🦩🌅💗", answer: "Flamingo",      category: "hayvan" },
  { emojis: "🦚🌈",    answer: "Tavus Kuşu",    category: "hayvan" },
  { emojis: "🐬🌊🏊", answer: "Yunus",         category: "hayvan" },
  { emojis: "🐳🌊💦", answer: "Balina",        category: "hayvan" },
  { emojis: "🦈🩸🌊", answer: "Köpekbalığı",   category: "hayvan" },
  { emojis: "🐙🌊8️⃣", answer: "Ahtapot",      category: "hayvan" },
  { emojis: "🦞🦀🌊", answer: "Istakoz",       category: "hayvan" },
  { emojis: "🐝🍯🌻", answer: "Arı",           category: "hayvan" },
  { emojis: "🦋🌸🌈", answer: "Kelebek",       category: "hayvan" },
  { emojis: "🦔🌳🍃", answer: "Kirpi",         category: "hayvan" },
  { emojis: "🐌🌧️🐚", answer: "Salyangoz",    category: "hayvan" },
  { emojis: "🐊🐊💧", answer: "Timsah",        category: "hayvan" },
  { emojis: "🦎🌵☀️", answer: "Kertenkele",   category: "hayvan" },
  { emojis: "🐝➕🐝➕🐝",answer: "Arı Kolonisi",category: "hayvan" },

  // ============================================================
  // SPOR — sadece az tanıdık
  // ============================================================
  { emojis: "🏐🏖️",  answer: "Plaj Voleybolu", category: "spor" },
  { emojis: "🏓🏆",   answer: "Masa Tenisi",    category: "spor" },
  { emojis: "🏸🪶",   answer: "Badminton",      category: "spor" },
  { emojis: "🏒🧊",   answer: "Buz Hokeyi",     category: "spor" },
  { emojis: "🥊🩸💪", answer: "Boks",           category: "spor" },
  { emojis: "🥋🇯🇵",  answer: "Karate",         category: "spor" },
  { emojis: "🤼🩳",   answer: "Güreş",          category: "spor" },
  { emojis: "🏂❄️🏔️",answer: "Snowboard",      category: "spor" },
  { emojis: "🏄🌊",   answer: "Sörf",           category: "spor" },
  { emojis: "🚣🌊",   answer: "Kürek",          category: "spor" },
  { emojis: "🤸💃",   answer: "Jimnastik",      category: "spor" },
  { emojis: "🧗🪨",   answer: "Kaya Tırmanışı", category: "spor" },
  { emojis: "🏋️💪",   answer: "Halter",         category: "spor" },
  { emojis: "🤾⚽",   answer: "Hentbol",        category: "spor" },
  { emojis: "🏌️⛳",   answer: "Golf",           category: "spor" },
  { emojis: "🎯🏹",   answer: "Okçuluk",        category: "spor" },
  { emojis: "🎳🥎",   answer: "Bovling",        category: "spor" },
  { emojis: "⛸️❄️",   answer: "Buz Pateni",     category: "spor" },
  { emojis: "🏇🐎",   answer: "At Yarışı",      category: "spor" },
  { emojis: "🤽🌊⚽", answer: "Sutopu",         category: "spor" },
  { emojis: "🤺⚔️",   answer: "Eskrim",         category: "spor" },
  { emojis: "🚵⛰️",   answer: "Dağ Bisikleti",  category: "spor" },
  { emojis: "🎣🐟",   answer: "Balıkçılık",     category: "spor" },
  { emojis: "🤿🌊🐠", answer: "Dalış",          category: "spor" },
  { emojis: "🎱🪀",   answer: "Bilardo",        category: "spor" },
  { emojis: "🪂✈️",   answer: "Paraşüt",        category: "spor" },

  // ============================================================
  // MESLEK — kombo ile
  // ============================================================
  { emojis: "👨‍⚕️🏥💊",answer: "Doktor",        category: "meslek" },
  { emojis: "👨‍🍳🍳🥘",answer: "Aşçı",          category: "meslek" },
  { emojis: "👨‍🏫📚🏫",answer: "Öğretmen",      category: "meslek" },
  { emojis: "👨‍🚒🔥🚒",answer: "İtfaiyeci",     category: "meslek" },
  { emojis: "👮🚓🚨", answer: "Polis",          category: "meslek" },
  { emojis: "👨‍🌾🌾🚜",answer: "Çiftçi",        category: "meslek" },
  { emojis: "👨‍🔬🔬⚗️",answer: "Bilim İnsanı",  category: "meslek" },
  { emojis: "👨‍🚀🚀🌌",answer: "Astronot",      category: "meslek" },
  { emojis: "👨‍✈️✈️☁️",answer: "Pilot",         category: "meslek" },
  { emojis: "👨‍🎨🎨🖼️",answer: "Ressam",        category: "meslek" },
  { emojis: "👨‍💻💻⌨️",answer: "Yazılımcı",     category: "meslek" },
  { emojis: "👨‍⚖️⚖️📜",answer: "Hakim",         category: "meslek" },
  { emojis: "👷🧱🔨", answer: "İnşaatçı",      category: "meslek" },
  { emojis: "🕵️🔍🎩", answer: "Dedektif",      category: "meslek" },
  { emojis: "💂🪖🎖️",answer: "Asker",          category: "meslek" },
  { emojis: "🧙🪄✨", answer: "Sihirbaz",      category: "meslek" },
  { emojis: "🥷⚔️🌃", answer: "Ninja",         category: "meslek" },
  { emojis: "🤡🎈🎪", answer: "Palyaço",       category: "meslek" },

  // ============================================================
  // DOĞA — kombo ile
  // ============================================================
  { emojis: "🌳🌲🌴", answer: "Orman",          category: "doga" },
  { emojis: "🌵🏜️☀️", answer: "Çöl",            category: "doga" },
  { emojis: "🌷🌹🌻", answer: "Çiçek Bahçesi",  category: "doga" },
  { emojis: "🍄🌳🌧️", answer: "Mantar",        category: "doga" },
  { emojis: "🏔️❄️🌨️",answer: "Karlı Dağ",    category: "doga" },
  { emojis: "🌋🔥💨", answer: "Volkan Patlaması",category: "doga" },
  { emojis: "🏖️🌴☀️", answer: "Tropik Plaj",   category: "doga" },
  { emojis: "🌊🌊🌊", answer: "Okyanus",        category: "doga" },
  { emojis: "❄️☁️🥶",answer: "Kar Fırtınası",  category: "doga" },
  { emojis: "🌧️☔🌈", answer: "Yağmurdan Sonra",category: "doga" },
  { emojis: "⚡🌩️⛈️", answer: "Fırtına",        category: "doga" },
  { emojis: "🌪️💨🏚️",answer: "Hortum",         category: "doga" },
  { emojis: "🌅🌄🌇", answer: "Gün Doğumu",     category: "doga" },
  { emojis: "🌙🌟🌌", answer: "Yıldızlı Gece",  category: "doga" },
  { emojis: "🏞️🌲🦌", answer: "Milli Park",    category: "doga" },

  // ============================================================
  // ARAÇ — kombo ile
  // ============================================================
  { emojis: "🚗💨🏎️", answer: "Yarış Arabası",  category: "arac" },
  { emojis: "🏍️💨💀", answer: "Motosiklet",     category: "arac" },
  { emojis: "🚌🏫👦", answer: "Okul Servisi",   category: "arac" },
  { emojis: "🚚📦",   answer: "Kargo Kamyonu",  category: "arac" },
  { emojis: "🚜🌾👨‍🌾",answer: "Traktör",       category: "arac" },
  { emojis: "✈️🛫🌍", answer: "Yolcu Uçağı",    category: "arac" },
  { emojis: "🚁⚕️🏥", answer: "Ambulans Helikopteri",category: "arac" },
  { emojis: "🚀🌌🌕", answer: "Uzay Roketi",    category: "arac" },
  { emojis: "⛵🌊🏝️",answer: "Yelkenli",        category: "arac" },
  { emojis: "🚢⚓🌊", answer: "Gemi",            category: "arac" },
  { emojis: "🛸👽🌌", answer: "UFO",             category: "arac" },
  { emojis: "🚂💨🌫️",answer: "Lokomotif",       category: "arac" },
  { emojis: "🚇🚉🏙️", answer: "Metro",          category: "arac" },

  // ============================================================
  // EŞYA — kombo ile
  // ============================================================
  { emojis: "💡✨💭", answer: "Fikir",          category: "esya" },
  { emojis: "🔑🚪🏠", answer: "Anahtar",        category: "esya" },
  { emojis: "🕯️🌙🪔",answer: "Mum",            category: "esya" },
  { emojis: "⏰😴🛌", answer: "Çalar Saat",     category: "esya" },
  { emojis: "⌛💀",   answer: "Zaman Doluyor",  category: "esya" },
  { emojis: "🎁🎀✨", answer: "Hediye Kutusu",  category: "esya" },
  { emojis: "📦📮🚚", answer: "Kargo",          category: "esya" },
  { emojis: "🛒🥖🥚", answer: "Market",         category: "esya" },
  { emojis: "🧸💕👶", answer: "Oyuncak Ayı",    category: "esya" },
  { emojis: "🎈🎉🎂", answer: "Parti",          category: "esya" },
  { emojis: "🪞👤🌟", answer: "Sihirli Ayna",   category: "esya" },
  { emojis: "🧹🧙‍♀️🌙",answer: "Cadı Süpürgesi",category: "esya" },
  { emojis: "🛠️🔧🔨",answer: "Tamir Seti",     category: "esya" },
  { emojis: "🧴🚿💧", answer: "Şampuan",        category: "esya" },
  { emojis: "🪥🦷✨", answer: "Diş Fırçası",    category: "esya" },
  { emojis: "📷📸🌅", answer: "Fotoğraf",       category: "esya" },
  { emojis: "💻⌨️👨‍💻",answer: "Bilgisayar",    category: "esya" },
  { emojis: "📱📲💬", answer: "Mesajlaşma",     category: "esya" },
  { emojis: "📺📡🎬", answer: "Televizyon",     category: "esya" },

  // ============================================================
  // MÜZİK — kombo ile
  // ============================================================
  { emojis: "🎸🎤🤘", answer: "Rock Konseri",   category: "muzik" },
  { emojis: "🎻🎼🎩", answer: "Klasik Müzik",   category: "muzik" },
  { emojis: "🥁🪘💥", answer: "Davul",          category: "muzik" },
  { emojis: "🎷🌃🎶", answer: "Caz",            category: "muzik" },
  { emojis: "🎺📯📣", answer: "Trompet",        category: "muzik" },
  { emojis: "🎹🎼👨‍🎨",answer: "Piyano",        category: "muzik" },
  { emojis: "🎤🎵💃", answer: "Şarkı",          category: "muzik" },
  { emojis: "🎧🎵👤", answer: "Müzik Dinleme",  category: "muzik" },
  { emojis: "🪗🎵🇹🇷",answer: "Akordeon",       category: "muzik" },
  { emojis: "🔔⛪🎵",answer: "Kilise Çanı",    category: "muzik" },

  // ============================================================
  // OKUL — kombo ile
  // ============================================================
  { emojis: "📚🎒🏫", answer: "Okul",           category: "okul" },
  { emojis: "🎓👨‍🎓📜",answer: "Mezuniyet",    category: "okul" },
  { emojis: "📝✏️📒", answer: "Ödev",           category: "okul" },
  { emojis: "🧮🔢➕", answer: "Matematik",     category: "okul" },
  { emojis: "🔬⚗️🧪", answer: "Kimya",          category: "okul" },
  { emojis: "🌍🗺️🧭", answer: "Coğrafya",     category: "okul" },
  { emojis: "📖🏛️📜",answer: "Tarih",          category: "okul" },
  { emojis: "🎨🖌️🖼️",answer: "Resim Dersi",  category: "okul" },
  { emojis: "⚽🏀🏐", answer: "Beden Eğitimi", category: "okul" }
];
