/* Emoji Quiz - question pool (500+ entries)
 * To add questions, append to QUESTIONS. Each entry has:
 *   emojis    : the emoji clue (string)
 *   answer    : correct answer (Turkish)
 *   category  : category id (see CATEGORY_LABELS in script.js)
 *
 * Categories: yemek, sehir, deyim, film, dunya, hayvan, spor,
 *             meslek, doga, renk, vucut, giysi, arac, esya, muzik,
 *             okul, duygu
 */
window.QUESTIONS = [
  // ============================================================
  // YEMEK (Food) — 60
  // ============================================================
  { emojis: "🥩🍢", answer: "Şiş Kebap", category: "yemek" },
  { emojis: "🍯🌰", answer: "Baklava", category: "yemek" },
  { emojis: "☕🇹🇷", answer: "Türk Kahvesi", category: "yemek" },
  { emojis: "🍆🍅🥩", answer: "Karnıyarık", category: "yemek" },
  { emojis: "🥩🍞🌯", answer: "Döner", category: "yemek" },
  { emojis: "🥟🥩", answer: "Mantı", category: "yemek" },
  { emojis: "🍅🥒🍞🧅", answer: "Menemen", category: "yemek" },
  { emojis: "🍵🌿", answer: "Çay", category: "yemek" },
  { emojis: "🥛🍚🍮", answer: "Sütlaç", category: "yemek" },
  { emojis: "🐑🍚", answer: "Pilav", category: "yemek" },
  { emojis: "🍕", answer: "Pizza", category: "yemek" },
  { emojis: "🍔", answer: "Hamburger", category: "yemek" },
  { emojis: "🌭", answer: "Sosisli", category: "yemek" },
  { emojis: "🥪", answer: "Sandviç", category: "yemek" },
  { emojis: "🌮", answer: "Taco", category: "yemek" },
  { emojis: "🌯", answer: "Dürüm", category: "yemek" },
  { emojis: "🍝", answer: "Makarna", category: "yemek" },
  { emojis: "🍜", answer: "Erişte", category: "yemek" },
  { emojis: "🍣", answer: "Suşi", category: "yemek" },
  { emojis: "🍿", answer: "Patlamış Mısır", category: "yemek" },
  { emojis: "🍞", answer: "Ekmek", category: "yemek" },
  { emojis: "🥖", answer: "Baget", category: "yemek" },
  { emojis: "🥐", answer: "Kruvasan", category: "yemek" },
  { emojis: "🥯", answer: "Simit", category: "yemek" },
  { emojis: "🧀", answer: "Peynir", category: "yemek" },
  { emojis: "🥚", answer: "Yumurta", category: "yemek" },
  { emojis: "🍳", answer: "Sahanda Yumurta", category: "yemek" },
  { emojis: "🥞", answer: "Krep", category: "yemek" },
  { emojis: "🧇", answer: "Waffle", category: "yemek" },
  { emojis: "🥓", answer: "Pastırma", category: "yemek" },
  { emojis: "🍗", answer: "Tavuk Budu", category: "yemek" },
  { emojis: "🍖", answer: "Et", category: "yemek" },
  { emojis: "🥗", answer: "Salata", category: "yemek" },
  { emojis: "🥣", answer: "Çorba", category: "yemek" },
  { emojis: "🍮", answer: "Krem Karamel", category: "yemek" },
  { emojis: "🍦", answer: "Dondurma", category: "yemek" },
  { emojis: "🍰", answer: "Pasta", category: "yemek" },
  { emojis: "🎂", answer: "Doğum Günü Pastası", category: "yemek" },
  { emojis: "🥧", answer: "Turta", category: "yemek" },
  { emojis: "🍪", answer: "Kurabiye", category: "yemek" },
  { emojis: "🍩", answer: "Donut", category: "yemek" },
  { emojis: "🍫", answer: "Çikolata", category: "yemek" },
  { emojis: "🍬", answer: "Şeker", category: "yemek" },
  { emojis: "🍭", answer: "Lolipop", category: "yemek" },
  { emojis: "🍑", answer: "Şeftali", category: "yemek" },
  { emojis: "🍓", answer: "Çilek", category: "yemek" },
  { emojis: "🍇", answer: "Üzüm", category: "yemek" },
  { emojis: "🍌", answer: "Muz", category: "yemek" },
  { emojis: "🍎", answer: "Elma", category: "yemek" },
  { emojis: "🍐", answer: "Armut", category: "yemek" },
  { emojis: "🍊", answer: "Portakal", category: "yemek" },
  { emojis: "🥭", answer: "Mango", category: "yemek" },
  { emojis: "🥑", answer: "Avokado", category: "yemek" },
  { emojis: "🥥", answer: "Hindistan Cevizi", category: "yemek" },
  { emojis: "🍍", answer: "Ananas", category: "yemek" },
  { emojis: "🍋", answer: "Limon", category: "yemek" },
  { emojis: "🥝", answer: "Kivi", category: "yemek" },
  { emojis: "🍒", answer: "Kiraz", category: "yemek" },
  { emojis: "🍉", answer: "Karpuz", category: "yemek" },
  { emojis: "🍈", answer: "Kavun", category: "yemek" },

  // ============================================================
  // ŞEHİR (City) — 35
  // ============================================================
  { emojis: "🌉🕌", answer: "İstanbul", category: "sehir" },
  { emojis: "🎈🪨", answer: "Kapadokya", category: "sehir" },
  { emojis: "⛵🌊", answer: "Bodrum", category: "sehir" },
  { emojis: "🛁💧🤍", answer: "Pamukkale", category: "sehir" },
  { emojis: "🏛️🇹🇷", answer: "Ankara", category: "sehir" },
  { emojis: "☀️🏝️", answer: "Antalya", category: "sehir" },
  { emojis: "🚢⛴️", answer: "İzmir", category: "sehir" },
  { emojis: "🌶️🥙", answer: "Adana", category: "sehir" },
  { emojis: "🌋🎿", answer: "Erciyes", category: "sehir" },
  { emojis: "🎓🏫🇹🇷", answer: "Eskişehir", category: "sehir" },
  { emojis: "🌹🇹🇷", answer: "Isparta", category: "sehir" },
  { emojis: "🍇🇹🇷", answer: "Manisa", category: "sehir" },
  { emojis: "🐟🌊🇹🇷", answer: "Trabzon", category: "sehir" },
  { emojis: "🌳🐻🇹🇷", answer: "Bolu", category: "sehir" },
  { emojis: "🍒🇹🇷", answer: "Tekirdağ", category: "sehir" },
  { emojis: "🐢🇹🇷", answer: "Çanakkale", category: "sehir" },
  { emojis: "🌸🇹🇷", answer: "Yalova", category: "sehir" },
  { emojis: "🥖🇹🇷", answer: "Edirne", category: "sehir" },
  { emojis: "⛪🇹🇷", answer: "Mardin", category: "sehir" },
  { emojis: "🍑🌳🇹🇷", answer: "Bursa", category: "sehir" },
  { emojis: "🗼🇫🇷", answer: "Paris", category: "sehir" },
  { emojis: "🗽🌉", answer: "New York", category: "sehir" },
  { emojis: "🐼🇨🇳", answer: "Pekin", category: "sehir" },
  { emojis: "🍕🇮🇹", answer: "Roma", category: "sehir" },
  { emojis: "⚽🇪🇸", answer: "Madrid", category: "sehir" },
  { emojis: "🎰🌃", answer: "Las Vegas", category: "sehir" },
  { emojis: "🎬⭐🌴", answer: "Hollywood", category: "sehir" },
  { emojis: "🏰🇬🇧", answer: "Londra", category: "sehir" },
  { emojis: "⛩️🥋", answer: "Tokyo", category: "sehir" },
  { emojis: "🍻🥨", answer: "Münih", category: "sehir" },
  { emojis: "🐫🏜️🇦🇪", answer: "Dubai", category: "sehir" },
  { emojis: "🌊🛶🇮🇹", answer: "Venedik", category: "sehir" },
  { emojis: "🛕🇮🇳", answer: "Delhi", category: "sehir" },
  { emojis: "🦅🏛️🇺🇸", answer: "Washington", category: "sehir" },
  { emojis: "🏖️🌴🇧🇷", answer: "Rio", category: "sehir" },

  // ============================================================
  // ATASÖZÜ / DEYİM — 35
  // ============================================================
  { emojis: "🐢🐢🐢", answer: "Yavaş ama emin", category: "deyim" },
  { emojis: "💧💧🌊", answer: "Damlaya damlaya göl olur", category: "deyim" },
  { emojis: "🪨🐦🐦", answer: "Bir taşla iki kuş", category: "deyim" },
  { emojis: "🤐🥇", answer: "Sükut altındır", category: "deyim" },
  { emojis: "🌳🍎😋", answer: "Armut piş ağzıma düş", category: "deyim" },
  { emojis: "🐺☁️🐺", answer: "Kurtla yatan kurtla kalkar", category: "deyim" },
  { emojis: "🏃💨🐢", answer: "Acele işe şeytan karışır", category: "deyim" },
  { emojis: "👁️👁️👃", answer: "Görmemiş görmüş", category: "deyim" },
  { emojis: "☀️🌧️🤝", answer: "Dost kara günde belli olur", category: "deyim" },
  { emojis: "🍇👀🍇", answer: "Üzüm üzüme baka baka kararır", category: "deyim" },
  { emojis: "🌱➡️🌾", answer: "Ne ekersen onu biçersin", category: "deyim" },
  { emojis: "🌾📦⏰", answer: "Sakla samanı gelir zamanı", category: "deyim" },
  { emojis: "🍯👆👅", answer: "Bal tutan parmağını yalar", category: "deyim" },
  { emojis: "🐔😴🌾", answer: "Aç tavuk düşünde darı görür", category: "deyim" },
  { emojis: "👅➡️🤕", answer: "Dilden çıkan başa gelir", category: "deyim" },
  { emojis: "🍯💬🐍", answer: "Tatlı dil yılanı deliğinden çıkarır", category: "deyim" },
  { emojis: "👁️❌💔", answer: "Gözden ırak olan gönülden de ırak olur", category: "deyim" },
  { emojis: "❤️❤️🎉", answer: "İki gönül bir olunca samanlık seyran olur", category: "deyim" },
  { emojis: "🕯️⬇️❌", answer: "Mum dibine ışık vermez", category: "deyim" },
  { emojis: "🛏️📏👣", answer: "Ayağını yorganına göre uzat", category: "deyim" },
  { emojis: "👤➕👤➡️💪", answer: "Birlikten kuvvet doğar", category: "deyim" },
  { emojis: "⏰💰", answer: "Vakit nakittir", category: "deyim" },
  { emojis: "🦅🦅🪺", answer: "Yuvayı dişi kuş yapar", category: "deyim" },
  { emojis: "🌤️⏰", answer: "Fırsat bu fırsat", category: "deyim" },
  { emojis: "💔🩹", answer: "Yara izi kalır", category: "deyim" },
  { emojis: "🌙🌟⏰", answer: "Gece gündüz çalışmak", category: "deyim" },
  { emojis: "🐸🌊", answer: "Kurbağa gibi yaşamak", category: "deyim" },
  { emojis: "🧠➡️🗣️", answer: "Önce düşün sonra konuş", category: "deyim" },
  { emojis: "🧘🎯", answer: "Sabreden derviş muradına ermiş", category: "deyim" },
  { emojis: "🐔🐔🐔🐺", answer: "Sayılı koyunu kurt yemez", category: "deyim" },
  { emojis: "👃➡️🍯", answer: "Kokuyu alan arıdır", category: "deyim" },
  { emojis: "🌳🍎⬇️", answer: "Armut dibine düşer", category: "deyim" },
  { emojis: "🚪➡️🌹", answer: "Her güzel yolculuk biter", category: "deyim" },
  { emojis: "📖🧠", answer: "Kitap insanın dostudur", category: "deyim" },
  { emojis: "🤝💪", answer: "El elden üstündür", category: "deyim" },

  // ============================================================
  // FİLM / DİZİ — 60
  // ============================================================
  { emojis: "👨‍👦💔", answer: "Babam ve Oğlum", category: "film" },
  { emojis: "🚀👽😂", answer: "G.O.R.A.", category: "film" },
  { emojis: "💪😂🇹🇷", answer: "Recep İvedik", category: "film" },
  { emojis: "🌹🍂💔", answer: "Yaprak Dökümü", category: "film" },
  { emojis: "🌹🍷❤️", answer: "Aşk-ı Memnu", category: "film" },
  { emojis: "🐺🇹🇷👮", answer: "Kurtlar Vadisi", category: "film" },
  { emojis: "🏰👑📜", answer: "Muhteşem Yüzyıl", category: "film" },
  { emojis: "🥋👴🇹🇷", answer: "Karadayı", category: "film" },
  { emojis: "🦁👑", answer: "Aslan Kral", category: "film" },
  { emojis: "🐭🧀", answer: "Tom ve Jerry", category: "film" },
  { emojis: "🦇🌃", answer: "Batman", category: "film" },
  { emojis: "🕷️👨", answer: "Örümcek Adam", category: "film" },
  { emojis: "⚔️🌌🚀", answer: "Yıldız Savaşları", category: "film" },
  { emojis: "🐠🌊🔍", answer: "Kayıp Balık Nemo", category: "film" },
  { emojis: "🍎🐍🌳", answer: "Adem ile Havva", category: "film" },
  { emojis: "🏠🐺🐷🐷🐷", answer: "Üç Küçük Domuz", category: "film" },
  { emojis: "❄️👸⛄", answer: "Karlar Ülkesi", category: "film" },
  { emojis: "👸🐸🤴", answer: "Prenses ve Kurbağa", category: "film" },
  { emojis: "🏰🌹👹", answer: "Güzel ve Çirkin", category: "film" },
  { emojis: "🐟👶🌊", answer: "Köpek Balığı (Jaws)", category: "film" },
  { emojis: "🦖🦕🏝️", answer: "Jurassic Park", category: "film" },
  { emojis: "💍🌋👤", answer: "Yüzüklerin Efendisi", category: "film" },
  { emojis: "⚡🧙‍♂️🏰", answer: "Harry Potter", category: "film" },
  { emojis: "🤖🚀⚙️", answer: "Transformers", category: "film" },
  { emojis: "🚢❄️💔", answer: "Titanic", category: "film" },
  { emojis: "👽🚲🌕", answer: "E.T.", category: "film" },
  { emojis: "🎭🃏", answer: "Joker", category: "film" },
  { emojis: "🦸🦸🦸", answer: "Yenilmezler", category: "film" },
  { emojis: "🕶️💊🟢", answer: "Matrix", category: "film" },
  { emojis: "🦍🍌", answer: "King Kong", category: "film" },
  { emojis: "🐙🌊⚓", answer: "Karayip Korsanları", category: "film" },
  { emojis: "🎩🐰🪄", answer: "Sihirbaz", category: "film" },
  { emojis: "🍄🍄👑", answer: "Süper Mario", category: "film" },
  { emojis: "🐝🐝🍯", answer: "Arı Maya", category: "film" },
  { emojis: "🐭👨‍🍳", answer: "Ratatuy", category: "film" },
  { emojis: "🚗💨🏁", answer: "Hızlı ve Öfkeli", category: "film" },
  { emojis: "🚀🌌👨‍🚀", answer: "Yıldızlararası", category: "film" },
  { emojis: "🤖❤️🌍", answer: "Wall-E", category: "film" },
  { emojis: "🦖🌳👨", answer: "Tarzan", category: "film" },
  { emojis: "👻👻🏚️", answer: "Hayalet Avcıları", category: "film" },
  { emojis: "🚪🚪🚪🤔", answer: "3 Adam", category: "film" },
  { emojis: "🇹🇷⚽😢", answer: "Cüneyt Arkın", category: "film" },
  { emojis: "🏖️🌊🇹🇷", answer: "Eyvah Eyvah", category: "film" },
  { emojis: "🚌🇹🇷😂", answer: "Yahşi Batı", category: "film" },
  { emojis: "🏘️👨‍👩‍👧", answer: "Aile Arasında", category: "film" },
  { emojis: "🍷🌃💔", answer: "Bir Aşk Hikayesi", category: "film" },
  { emojis: "📖✏️👶", answer: "Selvi Boylum Al Yazmalım", category: "film" },
  { emojis: "🌊🐟🇹🇷", answer: "Issız Adam", category: "film" },
  { emojis: "🎤🎵😂", answer: "Vizontele", category: "film" },
  { emojis: "🚗💨🐶", answer: "Kınalı Hanzo", category: "film" },
  { emojis: "🚓👮💪", answer: "Polis Akademisi", category: "film" },
  { emojis: "👰👨‍🦰💔", answer: "Düğün Dernek", category: "film" },
  { emojis: "🏀🏀🇹🇷", answer: "Hababam Sınıfı", category: "film" },
  { emojis: "🐺🚓", answer: "Behzat Ç.", category: "film" },
  { emojis: "👰❤️🧑‍🦱", answer: "Sen Çal Kapımı", category: "film" },
  { emojis: "🌹🏠❤️", answer: "Erkenci Kuş", category: "film" },
  { emojis: "🏠💍❤️", answer: "Kara Sevda", category: "film" },
  { emojis: "👮‍♀️🔍", answer: "Çukur", category: "film" },
  { emojis: "🚪👤🗝️", answer: "Diriliş Ertuğrul", category: "film" },
  { emojis: "⚔️👑🌳", answer: "Kuruluş Osman", category: "film" },

  // ============================================================
  // DÜNYA / GENEL — 50
  // ============================================================
  { emojis: "🌍🌎🌏", answer: "Dünya", category: "dunya" },
  { emojis: "🌞🌙⭐", answer: "Gökyüzü", category: "dunya" },
  { emojis: "🚀🌕", answer: "Uzay", category: "dunya" },
  { emojis: "🎄🎁🎅", answer: "Yılbaşı", category: "dunya" },
  { emojis: "🎂🎉🎈", answer: "Doğum Günü", category: "dunya" },
  { emojis: "💍👰🤵", answer: "Düğün", category: "dunya" },
  { emojis: "🌹❤️💕", answer: "Sevgililer Günü", category: "dunya" },
  { emojis: "🎆🎇🌃", answer: "Havai Fişek", category: "dunya" },
  { emojis: "🏆🥇🎖️", answer: "Şampiyon", category: "dunya" },
  { emojis: "📚🎓👨‍🎓", answer: "Mezuniyet", category: "dunya" },
  { emojis: "🎤🎸🎵", answer: "Konser", category: "dunya" },
  { emojis: "🎬🎥🍿", answer: "Sinema", category: "dunya" },
  { emojis: "🎨🖌️🖼️", answer: "Resim", category: "dunya" },
  { emojis: "📷📸", answer: "Fotoğraf", category: "dunya" },
  { emojis: "💻⌨️🖱️", answer: "Bilgisayar", category: "dunya" },
  { emojis: "📱☎️", answer: "Telefon", category: "dunya" },
  { emojis: "📺📡", answer: "Televizyon", category: "dunya" },
  { emojis: "⌚⏰", answer: "Saat", category: "dunya" },
  { emojis: "💰💵💴", answer: "Para", category: "dunya" },
  { emojis: "🏦🏧💳", answer: "Banka", category: "dunya" },
  { emojis: "🛒🛍️", answer: "Alışveriş", category: "dunya" },
  { emojis: "🏥💊💉", answer: "Hastane", category: "dunya" },
  { emojis: "🚓🚨👮", answer: "Polis", category: "dunya" },
  { emojis: "🚒🔥👨‍🚒", answer: "İtfaiye", category: "dunya" },
  { emojis: "✈️🛫🌍", answer: "Tatil", category: "dunya" },
  { emojis: "🏨🛏️🔑", answer: "Otel", category: "dunya" },
  { emojis: "🏖️🌴☀️", answer: "Plaj", category: "dunya" },
  { emojis: "⛷️🎿❄️", answer: "Kayak", category: "dunya" },
  { emojis: "🎢🎡🎠", answer: "Lunapark", category: "dunya" },
  { emojis: "🌋🔥💨", answer: "Volkan", category: "dunya" },
  { emojis: "🌊🏊🌅", answer: "Deniz", category: "dunya" },
  { emojis: "🏞️🏔️🌲", answer: "Doğa", category: "dunya" },
  { emojis: "🚇🚆🚂", answer: "Tren", category: "dunya" },
  { emojis: "🛸👽🌌", answer: "UFO", category: "dunya" },
  { emojis: "🧙‍♂️🪄✨", answer: "Sihir", category: "dunya" },
  { emojis: "👻🎃🦇", answer: "Cadılar Bayramı", category: "dunya" },
  { emojis: "🌈☔🌧️", answer: "Gökkuşağı", category: "dunya" },
  { emojis: "🎪🎭🤹", answer: "Sirk", category: "dunya" },
  { emojis: "🚁⚓🚢", answer: "Ulaşım", category: "dunya" },
  { emojis: "💎💰👑", answer: "Hazine", category: "dunya" },
  { emojis: "🗺️🧭⛰️", answer: "Macera", category: "dunya" },
  { emojis: "📅📆🗓️", answer: "Takvim", category: "dunya" },
  { emojis: "✉️📮📬", answer: "Mektup", category: "dunya" },
  { emojis: "🔑🚪🏠", answer: "Anahtar", category: "dunya" },
  { emojis: "🕯️🔥💡", answer: "Işık", category: "dunya" },
  { emojis: "🛁🚿💧", answer: "Banyo", category: "dunya" },
  { emojis: "🧹🪣🧽", answer: "Temizlik", category: "dunya" },
  { emojis: "🛏️😴💤", answer: "Uyku", category: "dunya" },
  { emojis: "🍴🥄🥢", answer: "Yemek Vakti", category: "dunya" },
  { emojis: "📝✏️📒", answer: "Yazı", category: "dunya" },

  // ============================================================
  // HAYVAN — 60
  // ============================================================
  { emojis: "🐕", answer: "Köpek", category: "hayvan" },
  { emojis: "🐈", answer: "Kedi", category: "hayvan" },
  { emojis: "🐘", answer: "Fil", category: "hayvan" },
  { emojis: "🦁", answer: "Aslan", category: "hayvan" },
  { emojis: "🐅", answer: "Kaplan", category: "hayvan" },
  { emojis: "🐎", answer: "At", category: "hayvan" },
  { emojis: "🐄", answer: "İnek", category: "hayvan" },
  { emojis: "🐑", answer: "Koyun", category: "hayvan" },
  { emojis: "🐐", answer: "Keçi", category: "hayvan" },
  { emojis: "🐖", answer: "Domuz", category: "hayvan" },
  { emojis: "🐔", answer: "Tavuk", category: "hayvan" },
  { emojis: "🐓", answer: "Horoz", category: "hayvan" },
  { emojis: "🦆", answer: "Ördek", category: "hayvan" },
  { emojis: "🦃", answer: "Hindi", category: "hayvan" },
  { emojis: "🦢", answer: "Kuğu", category: "hayvan" },
  { emojis: "🐢", answer: "Kaplumbağa", category: "hayvan" },
  { emojis: "🐍", answer: "Yılan", category: "hayvan" },
  { emojis: "🦎", answer: "Kertenkele", category: "hayvan" },
  { emojis: "🐊", answer: "Timsah", category: "hayvan" },
  { emojis: "🐸", answer: "Kurbağa", category: "hayvan" },
  { emojis: "🐠", answer: "Balık", category: "hayvan" },
  { emojis: "🐬", answer: "Yunus", category: "hayvan" },
  { emojis: "🐳", answer: "Balina", category: "hayvan" },
  { emojis: "🦈", answer: "Köpekbalığı", category: "hayvan" },
  { emojis: "🦑", answer: "Kalamar", category: "hayvan" },
  { emojis: "🐙", answer: "Ahtapot", category: "hayvan" },
  { emojis: "🦞", answer: "Istakoz", category: "hayvan" },
  { emojis: "🦀", answer: "Yengeç", category: "hayvan" },
  { emojis: "🦐", answer: "Karides", category: "hayvan" },
  { emojis: "🐝", answer: "Arı", category: "hayvan" },
  { emojis: "🐜", answer: "Karınca", category: "hayvan" },
  { emojis: "🦋", answer: "Kelebek", category: "hayvan" },
  { emojis: "🐞", answer: "Uğur Böceği", category: "hayvan" },
  { emojis: "🕷️", answer: "Örümcek", category: "hayvan" },
  { emojis: "🐌", answer: "Salyangoz", category: "hayvan" },
  { emojis: "🐛", answer: "Tırtıl", category: "hayvan" },
  { emojis: "🦗", answer: "Çekirge", category: "hayvan" },
  { emojis: "🐺", answer: "Kurt", category: "hayvan" },
  { emojis: "🦊", answer: "Tilki", category: "hayvan" },
  { emojis: "🐻", answer: "Ayı", category: "hayvan" },
  { emojis: "🐼", answer: "Panda", category: "hayvan" },
  { emojis: "🐨", answer: "Koala", category: "hayvan" },
  { emojis: "🦘", answer: "Kanguru", category: "hayvan" },
  { emojis: "🦒", answer: "Zürafa", category: "hayvan" },
  { emojis: "🦏", answer: "Gergedan", category: "hayvan" },
  { emojis: "🦛", answer: "Su Aygırı", category: "hayvan" },
  { emojis: "🦌", answer: "Geyik", category: "hayvan" },
  { emojis: "🐪", answer: "Deve", category: "hayvan" },
  { emojis: "🐇", answer: "Tavşan", category: "hayvan" },
  { emojis: "🐹", answer: "Hamster", category: "hayvan" },
  { emojis: "🐭", answer: "Fare", category: "hayvan" },
  { emojis: "🦔", answer: "Kirpi", category: "hayvan" },
  { emojis: "🦇", answer: "Yarasa", category: "hayvan" },
  { emojis: "🦉", answer: "Baykuş", category: "hayvan" },
  { emojis: "🦅", answer: "Kartal", category: "hayvan" },
  { emojis: "🦜", answer: "Papağan", category: "hayvan" },
  { emojis: "🐧", answer: "Penguen", category: "hayvan" },
  { emojis: "🦩", answer: "Flamingo", category: "hayvan" },
  { emojis: "🦚", answer: "Tavus Kuşu", category: "hayvan" },
  { emojis: "🐦", answer: "Kuş", category: "hayvan" },

  // ============================================================
  // SPOR — 40
  // ============================================================
  { emojis: "⚽", answer: "Futbol", category: "spor" },
  { emojis: "🏀", answer: "Basketbol", category: "spor" },
  { emojis: "🏐", answer: "Voleybol", category: "spor" },
  { emojis: "🎾", answer: "Tenis", category: "spor" },
  { emojis: "🏓", answer: "Masa Tenisi", category: "spor" },
  { emojis: "🏸", answer: "Badminton", category: "spor" },
  { emojis: "🏒", answer: "Buz Hokeyi", category: "spor" },
  { emojis: "🏑", answer: "Hokey", category: "spor" },
  { emojis: "🏏", answer: "Kriket", category: "spor" },
  { emojis: "🥊", answer: "Boks", category: "spor" },
  { emojis: "🥋", answer: "Karate", category: "spor" },
  { emojis: "🤼", answer: "Güreş", category: "spor" },
  { emojis: "⛷️", answer: "Kayak", category: "spor" },
  { emojis: "🏂", answer: "Snowboard", category: "spor" },
  { emojis: "🏄", answer: "Sörf", category: "spor" },
  { emojis: "🚣", answer: "Kürek", category: "spor" },
  { emojis: "🏊", answer: "Yüzme", category: "spor" },
  { emojis: "🚴", answer: "Bisiklet", category: "spor" },
  { emojis: "🏃", answer: "Koşu", category: "spor" },
  { emojis: "🤸", answer: "Jimnastik", category: "spor" },
  { emojis: "🧗", answer: "Kaya Tırmanışı", category: "spor" },
  { emojis: "🏋️", answer: "Halter", category: "spor" },
  { emojis: "🤾", answer: "Hentbol", category: "spor" },
  { emojis: "🏌️", answer: "Golf", category: "spor" },
  { emojis: "🎯", answer: "Dart", category: "spor" },
  { emojis: "🎳", answer: "Bovling", category: "spor" },
  { emojis: "⛸️", answer: "Buz Pateni", category: "spor" },
  { emojis: "🛹", answer: "Kaykay", category: "spor" },
  { emojis: "🛼", answer: "Paten", category: "spor" },
  { emojis: "🏇", answer: "At Yarışı", category: "spor" },
  { emojis: "🤽", answer: "Sutopu", category: "spor" },
  { emojis: "🤺", answer: "Eskrim", category: "spor" },
  { emojis: "🚵", answer: "Dağ Bisikleti", category: "spor" },
  { emojis: "⛳", answer: "Golf Bayrağı", category: "spor" },
  { emojis: "🎣", answer: "Balıkçılık", category: "spor" },
  { emojis: "🥍", answer: "Lakros", category: "spor" },
  { emojis: "🤿", answer: "Dalış", category: "spor" },
  { emojis: "🎱", answer: "Bilardo", category: "spor" },
  { emojis: "🪂", answer: "Paraşüt", category: "spor" },
  { emojis: "🥏", answer: "Frizbi", category: "spor" },

  // ============================================================
  // MESLEK — 25
  // ============================================================
  { emojis: "👨‍⚕️", answer: "Doktor", category: "meslek" },
  { emojis: "👨‍🍳", answer: "Aşçı", category: "meslek" },
  { emojis: "👨‍🏫", answer: "Öğretmen", category: "meslek" },
  { emojis: "👨‍🚒", answer: "İtfaiyeci", category: "meslek" },
  { emojis: "👮", answer: "Polis", category: "meslek" },
  { emojis: "👨‍🌾", answer: "Çiftçi", category: "meslek" },
  { emojis: "👨‍🔧", answer: "Tamirci", category: "meslek" },
  { emojis: "👨‍🔬", answer: "Bilim İnsanı", category: "meslek" },
  { emojis: "👨‍🚀", answer: "Astronot", category: "meslek" },
  { emojis: "👨‍✈️", answer: "Pilot", category: "meslek" },
  { emojis: "👨‍🎨", answer: "Ressam", category: "meslek" },
  { emojis: "👨‍🎤", answer: "Şarkıcı", category: "meslek" },
  { emojis: "👨‍💻", answer: "Yazılımcı", category: "meslek" },
  { emojis: "👨‍⚖️", answer: "Hakim", category: "meslek" },
  { emojis: "👷", answer: "İnşaatçı", category: "meslek" },
  { emojis: "🕵️", answer: "Dedektif", category: "meslek" },
  { emojis: "🧑‍🚀", answer: "Astronot", category: "meslek" },
  { emojis: "🧑‍🏭", answer: "Fabrika İşçisi", category: "meslek" },
  { emojis: "💂", answer: "Asker", category: "meslek" },
  { emojis: "🤴", answer: "Prens", category: "meslek" },
  { emojis: "👸", answer: "Prenses", category: "meslek" },
  { emojis: "🧙", answer: "Sihirbaz", category: "meslek" },
  { emojis: "🧜", answer: "Denizkızı", category: "meslek" },
  { emojis: "🥷", answer: "Ninja", category: "meslek" },
  { emojis: "🤡", answer: "Palyaço", category: "meslek" },

  // ============================================================
  // DOĞA — 30
  // ============================================================
  { emojis: "🌳", answer: "Ağaç", category: "doga" },
  { emojis: "🌲", answer: "Çam", category: "doga" },
  { emojis: "🌴", answer: "Palmiye", category: "doga" },
  { emojis: "🌵", answer: "Kaktüs", category: "doga" },
  { emojis: "🌿", answer: "Yaprak", category: "doga" },
  { emojis: "🍀", answer: "Yonca", category: "doga" },
  { emojis: "🌷", answer: "Lale", category: "doga" },
  { emojis: "🌹", answer: "Gül", category: "doga" },
  { emojis: "🌻", answer: "Ayçiçeği", category: "doga" },
  { emojis: "🌼", answer: "Papatya", category: "doga" },
  { emojis: "🌸", answer: "Kiraz Çiçeği", category: "doga" },
  { emojis: "🍄", answer: "Mantar", category: "doga" },
  { emojis: "⛰️", answer: "Dağ", category: "doga" },
  { emojis: "🏔️", answer: "Karlı Dağ", category: "doga" },
  { emojis: "🌋", answer: "Volkan", category: "doga" },
  { emojis: "🏖️", answer: "Plaj", category: "doga" },
  { emojis: "🏜️", answer: "Çöl", category: "doga" },
  { emojis: "🌊", answer: "Deniz", category: "doga" },
  { emojis: "💧", answer: "Su Damlası", category: "doga" },
  { emojis: "🔥", answer: "Ateş", category: "doga" },
  { emojis: "❄️", answer: "Kar", category: "doga" },
  { emojis: "☀️", answer: "Güneş", category: "doga" },
  { emojis: "🌙", answer: "Ay", category: "doga" },
  { emojis: "⭐", answer: "Yıldız", category: "doga" },
  { emojis: "☁️", answer: "Bulut", category: "doga" },
  { emojis: "🌈", answer: "Gökkuşağı", category: "doga" },
  { emojis: "⚡", answer: "Şimşek", category: "doga" },
  { emojis: "🌧️", answer: "Yağmur", category: "doga" },
  { emojis: "❄️☁️", answer: "Kar Yağışı", category: "doga" },
  { emojis: "🌪️", answer: "Hortum", category: "doga" },

  // ============================================================
  // RENK — 12
  // ============================================================
  { emojis: "🔴", answer: "Kırmızı", category: "renk" },
  { emojis: "🟠", answer: "Turuncu", category: "renk" },
  { emojis: "🟡", answer: "Sarı", category: "renk" },
  { emojis: "🟢", answer: "Yeşil", category: "renk" },
  { emojis: "🔵", answer: "Mavi", category: "renk" },
  { emojis: "🟣", answer: "Mor", category: "renk" },
  { emojis: "🟤", answer: "Kahverengi", category: "renk" },
  { emojis: "⚫", answer: "Siyah", category: "renk" },
  { emojis: "⚪", answer: "Beyaz", category: "renk" },
  { emojis: "💗", answer: "Pembe", category: "renk" },
  { emojis: "🩶", answer: "Gri", category: "renk" },
  { emojis: "🩵", answer: "Açık Mavi", category: "renk" },

  // ============================================================
  // VÜCUT — 15
  // ============================================================
  { emojis: "👁️", answer: "Göz", category: "vucut" },
  { emojis: "👂", answer: "Kulak", category: "vucut" },
  { emojis: "👃", answer: "Burun", category: "vucut" },
  { emojis: "👄", answer: "Dudak", category: "vucut" },
  { emojis: "👅", answer: "Dil", category: "vucut" },
  { emojis: "🦷", answer: "Diş", category: "vucut" },
  { emojis: "🧠", answer: "Beyin", category: "vucut" },
  { emojis: "🫀", answer: "Kalp", category: "vucut" },
  { emojis: "🫁", answer: "Akciğer", category: "vucut" },
  { emojis: "💪", answer: "Pazı", category: "vucut" },
  { emojis: "🦾", answer: "Robot Kol", category: "vucut" },
  { emojis: "🦴", answer: "Kemik", category: "vucut" },
  { emojis: "🦵", answer: "Bacak", category: "vucut" },
  { emojis: "🦶", answer: "Ayak", category: "vucut" },
  { emojis: "✋", answer: "El", category: "vucut" },

  // ============================================================
  // GİYSİ — 15
  // ============================================================
  { emojis: "👕", answer: "Tişört", category: "giysi" },
  { emojis: "👔", answer: "Gömlek", category: "giysi" },
  { emojis: "👖", answer: "Pantolon", category: "giysi" },
  { emojis: "👗", answer: "Elbise", category: "giysi" },
  { emojis: "👘", answer: "Kimono", category: "giysi" },
  { emojis: "🧥", answer: "Mont", category: "giysi" },
  { emojis: "🧣", answer: "Atkı", category: "giysi" },
  { emojis: "🧤", answer: "Eldiven", category: "giysi" },
  { emojis: "🧦", answer: "Çorap", category: "giysi" },
  { emojis: "👞", answer: "Ayakkabı", category: "giysi" },
  { emojis: "👟", answer: "Spor Ayakkabı", category: "giysi" },
  { emojis: "👠", answer: "Topuklu", category: "giysi" },
  { emojis: "👢", answer: "Çizme", category: "giysi" },
  { emojis: "👒", answer: "Şapka", category: "giysi" },
  { emojis: "🎩", answer: "Silindir Şapka", category: "giysi" },

  // ============================================================
  // ARAÇ — 22
  // ============================================================
  { emojis: "🚗", answer: "Araba", category: "arac" },
  { emojis: "🚕", answer: "Taksi", category: "arac" },
  { emojis: "🚌", answer: "Otobüs", category: "arac" },
  { emojis: "🚎", answer: "Troleybüs", category: "arac" },
  { emojis: "🚓", answer: "Polis Arabası", category: "arac" },
  { emojis: "🚑", answer: "Ambulans", category: "arac" },
  { emojis: "🚒", answer: "İtfaiye Arabası", category: "arac" },
  { emojis: "🚚", answer: "Kamyonet", category: "arac" },
  { emojis: "🚛", answer: "TIR", category: "arac" },
  { emojis: "🚜", answer: "Traktör", category: "arac" },
  { emojis: "🏎️", answer: "Yarış Arabası", category: "arac" },
  { emojis: "🏍️", answer: "Motosiklet", category: "arac" },
  { emojis: "🚲", answer: "Bisiklet", category: "arac" },
  { emojis: "🛴", answer: "Scooter", category: "arac" },
  { emojis: "🚂", answer: "Lokomotif", category: "arac" },
  { emojis: "🚆", answer: "Tren", category: "arac" },
  { emojis: "🚇", answer: "Metro", category: "arac" },
  { emojis: "✈️", answer: "Uçak", category: "arac" },
  { emojis: "🚁", answer: "Helikopter", category: "arac" },
  { emojis: "🚀", answer: "Roket", category: "arac" },
  { emojis: "🛸", answer: "UFO", category: "arac" },
  { emojis: "⛵", answer: "Yelkenli", category: "arac" },

  // ============================================================
  // EŞYA — 35
  // ============================================================
  { emojis: "📺", answer: "Televizyon", category: "esya" },
  { emojis: "📻", answer: "Radyo", category: "esya" },
  { emojis: "📞", answer: "Telefon", category: "esya" },
  { emojis: "📱", answer: "Cep Telefonu", category: "esya" },
  { emojis: "💻", answer: "Dizüstü", category: "esya" },
  { emojis: "🖥️", answer: "Masaüstü", category: "esya" },
  { emojis: "⌨️", answer: "Klavye", category: "esya" },
  { emojis: "🖱️", answer: "Fare", category: "esya" },
  { emojis: "🖨️", answer: "Yazıcı", category: "esya" },
  { emojis: "📷", answer: "Fotoğraf Makinesi", category: "esya" },
  { emojis: "📹", answer: "Kamera", category: "esya" },
  { emojis: "💡", answer: "Ampul", category: "esya" },
  { emojis: "🔦", answer: "El Feneri", category: "esya" },
  { emojis: "🔋", answer: "Pil", category: "esya" },
  { emojis: "🔌", answer: "Fiş", category: "esya" },
  { emojis: "🪫", answer: "Boş Pil", category: "esya" },
  { emojis: "⏰", answer: "Çalar Saat", category: "esya" },
  { emojis: "⌛", answer: "Kum Saati", category: "esya" },
  { emojis: "🪑", answer: "Sandalye", category: "esya" },
  { emojis: "🛋️", answer: "Koltuk", category: "esya" },
  { emojis: "🛏️", answer: "Yatak", category: "esya" },
  { emojis: "🚪", answer: "Kapı", category: "esya" },
  { emojis: "🪞", answer: "Ayna", category: "esya" },
  { emojis: "🪟", answer: "Pencere", category: "esya" },
  { emojis: "🛒", answer: "Alışveriş Arabası", category: "esya" },
  { emojis: "🧴", answer: "Şampuan", category: "esya" },
  { emojis: "🧼", answer: "Sabun", category: "esya" },
  { emojis: "🪥", answer: "Diş Fırçası", category: "esya" },
  { emojis: "🧹", answer: "Süpürge", category: "esya" },
  { emojis: "🧺", answer: "Sepet", category: "esya" },
  { emojis: "🧸", answer: "Oyuncak Ayı", category: "esya" },
  { emojis: "🎈", answer: "Balon", category: "esya" },
  { emojis: "🎁", answer: "Hediye", category: "esya" },
  { emojis: "📦", answer: "Kutu", category: "esya" },
  { emojis: "🛠️", answer: "Alet", category: "esya" },

  // ============================================================
  // MÜZİK — 15
  // ============================================================
  { emojis: "🎸", answer: "Gitar", category: "muzik" },
  { emojis: "🎹", answer: "Piyano", category: "muzik" },
  { emojis: "🎻", answer: "Keman", category: "muzik" },
  { emojis: "🥁", answer: "Davul", category: "muzik" },
  { emojis: "🎷", answer: "Saksafon", category: "muzik" },
  { emojis: "🎺", answer: "Trompet", category: "muzik" },
  { emojis: "🪕", answer: "Banjo", category: "muzik" },
  { emojis: "🪘", answer: "Tahta Davul", category: "muzik" },
  { emojis: "🎤", answer: "Mikrofon", category: "muzik" },
  { emojis: "🎧", answer: "Kulaklık", category: "muzik" },
  { emojis: "🎵", answer: "Nota", category: "muzik" },
  { emojis: "🎼", answer: "Müzik", category: "muzik" },
  { emojis: "🪗", answer: "Akordeon", category: "muzik" },
  { emojis: "📯", answer: "Boru", category: "muzik" },
  { emojis: "🔔", answer: "Çan", category: "muzik" },

  // ============================================================
  // OKUL — 20
  // ============================================================
  { emojis: "📚", answer: "Kitap", category: "okul" },
  { emojis: "📓", answer: "Defter", category: "okul" },
  { emojis: "📒", answer: "Not Defteri", category: "okul" },
  { emojis: "📕", answer: "Ders Kitabı", category: "okul" },
  { emojis: "📖", answer: "Açık Kitap", category: "okul" },
  { emojis: "✏️", answer: "Kalem", category: "okul" },
  { emojis: "✒️", answer: "Dolma Kalem", category: "okul" },
  { emojis: "🖊️", answer: "Tükenmez", category: "okul" },
  { emojis: "🖍️", answer: "Pastel", category: "okul" },
  { emojis: "📝", answer: "Yazı", category: "okul" },
  { emojis: "📐", answer: "Cetvel", category: "okul" },
  { emojis: "📏", answer: "Cetvel", category: "okul" },
  { emojis: "📎", answer: "Ataç", category: "okul" },
  { emojis: "✂️", answer: "Makas", category: "okul" },
  { emojis: "🖇️", answer: "Zımba", category: "okul" },
  { emojis: "🎒", answer: "Sırt Çantası", category: "okul" },
  { emojis: "🏫", answer: "Okul", category: "okul" },
  { emojis: "🎓", answer: "Mezuniyet Kepi", category: "okul" },
  { emojis: "🧮", answer: "Abaküs", category: "okul" },
  { emojis: "🔬", answer: "Mikroskop", category: "okul" },

  // ============================================================
  // DUYGU — 15
  // ============================================================
  { emojis: "😀", answer: "Mutluluk", category: "duygu" },
  { emojis: "😢", answer: "Üzüntü", category: "duygu" },
  { emojis: "😡", answer: "Öfke", category: "duygu" },
  { emojis: "😨", answer: "Korku", category: "duygu" },
  { emojis: "😱", answer: "Şok", category: "duygu" },
  { emojis: "😴", answer: "Uyku", category: "duygu" },
  { emojis: "🤔", answer: "Düşünme", category: "duygu" },
  { emojis: "😍", answer: "Aşk", category: "duygu" },
  { emojis: "😂", answer: "Kahkaha", category: "duygu" },
  { emojis: "😎", answer: "Havalı", category: "duygu" },
  { emojis: "🤢", answer: "İğrenme", category: "duygu" },
  { emojis: "🥳", answer: "Kutlama", category: "duygu" },
  { emojis: "🥺", answer: "Yalvarma", category: "duygu" },
  { emojis: "😭", answer: "Ağlama", category: "duygu" },
  { emojis: "🤯", answer: "Şaşkınlık", category: "duygu" }
];
