/* English vocabulary pool — primary school level (~200 words across 10 categories).
 * Add words by appending to WORDS. Each entry:
 *   en       : English word
 *   tr       : Turkish translation
 *   emoji    : single illustrative emoji
 *   category : category id (see CATEGORY_LABELS in script.js)
 */
window.WORDS = [
  // ===================== animals (35) =====================
  { en: "Dog",       tr: "Köpek",        emoji: "🐕",  category: "animals" },
  { en: "Cat",       tr: "Kedi",         emoji: "🐈",  category: "animals" },
  { en: "Bird",      tr: "Kuş",          emoji: "🐦",  category: "animals" },
  { en: "Fish",      tr: "Balık",        emoji: "🐠",  category: "animals" },
  { en: "Horse",     tr: "At",           emoji: "🐎",  category: "animals" },
  { en: "Cow",       tr: "İnek",         emoji: "🐄",  category: "animals" },
  { en: "Sheep",     tr: "Koyun",        emoji: "🐑",  category: "animals" },
  { en: "Pig",       tr: "Domuz",        emoji: "🐖",  category: "animals" },
  { en: "Chicken",   tr: "Tavuk",        emoji: "🐔",  category: "animals" },
  { en: "Duck",      tr: "Ördek",        emoji: "🦆",  category: "animals" },
  { en: "Rabbit",    tr: "Tavşan",       emoji: "🐇",  category: "animals" },
  { en: "Mouse",     tr: "Fare",         emoji: "🐭",  category: "animals" },
  { en: "Lion",      tr: "Aslan",        emoji: "🦁",  category: "animals" },
  { en: "Tiger",     tr: "Kaplan",       emoji: "🐅",  category: "animals" },
  { en: "Bear",      tr: "Ayı",          emoji: "🐻",  category: "animals" },
  { en: "Wolf",      tr: "Kurt",         emoji: "🐺",  category: "animals" },
  { en: "Fox",       tr: "Tilki",        emoji: "🦊",  category: "animals" },
  { en: "Monkey",    tr: "Maymun",       emoji: "🐒",  category: "animals" },
  { en: "Elephant",  tr: "Fil",          emoji: "🐘",  category: "animals" },
  { en: "Giraffe",   tr: "Zürafa",       emoji: "🦒",  category: "animals" },
  { en: "Zebra",     tr: "Zebra",        emoji: "🦓",  category: "animals" },
  { en: "Camel",     tr: "Deve",         emoji: "🐪",  category: "animals" },
  { en: "Kangaroo",  tr: "Kanguru",      emoji: "🦘",  category: "animals" },
  { en: "Panda",     tr: "Panda",        emoji: "🐼",  category: "animals" },
  { en: "Snake",     tr: "Yılan",        emoji: "🐍",  category: "animals" },
  { en: "Frog",      tr: "Kurbağa",      emoji: "🐸",  category: "animals" },
  { en: "Turtle",    tr: "Kaplumbağa",   emoji: "🐢",  category: "animals" },
  { en: "Bee",       tr: "Arı",          emoji: "🐝",  category: "animals" },
  { en: "Butterfly", tr: "Kelebek",      emoji: "🦋",  category: "animals" },
  { en: "Spider",    tr: "Örümcek",      emoji: "🕷️",  category: "animals" },
  { en: "Owl",       tr: "Baykuş",       emoji: "🦉",  category: "animals" },
  { en: "Eagle",     tr: "Kartal",       emoji: "🦅",  category: "animals" },
  { en: "Dolphin",   tr: "Yunus",        emoji: "🐬",  category: "animals" },
  { en: "Shark",     tr: "Köpekbalığı",  emoji: "🦈",  category: "animals" },
  { en: "Penguin",   tr: "Penguen",      emoji: "🐧",  category: "animals" },

  // ===================== colors (12) =====================
  { en: "Red",     tr: "Kırmızı",    emoji: "🔴", category: "colors" },
  { en: "Blue",    tr: "Mavi",       emoji: "🔵", category: "colors" },
  { en: "Yellow",  tr: "Sarı",       emoji: "🟡", category: "colors" },
  { en: "Green",   tr: "Yeşil",      emoji: "🟢", category: "colors" },
  { en: "Orange",  tr: "Turuncu",    emoji: "🟠", category: "colors" },
  { en: "Purple",  tr: "Mor",        emoji: "🟣", category: "colors" },
  { en: "Pink",    tr: "Pembe",      emoji: "💗", category: "colors" },
  { en: "Brown",   tr: "Kahverengi", emoji: "🟤", category: "colors" },
  { en: "Black",   tr: "Siyah",      emoji: "⚫", category: "colors" },
  { en: "White",   tr: "Beyaz",      emoji: "⚪", category: "colors" },
  { en: "Gray",    tr: "Gri",        emoji: "🩶", category: "colors" },
  { en: "Gold",    tr: "Altın",      emoji: "🟨", category: "colors" },

  // ===================== numbers (15) =====================
  { en: "One",     tr: "Bir",   emoji: "1️⃣",  category: "numbers" },
  { en: "Two",     tr: "İki",   emoji: "2️⃣",  category: "numbers" },
  { en: "Three",   tr: "Üç",    emoji: "3️⃣",  category: "numbers" },
  { en: "Four",    tr: "Dört",  emoji: "4️⃣",  category: "numbers" },
  { en: "Five",    tr: "Beş",   emoji: "5️⃣",  category: "numbers" },
  { en: "Six",     tr: "Altı",  emoji: "6️⃣",  category: "numbers" },
  { en: "Seven",   tr: "Yedi",  emoji: "7️⃣",  category: "numbers" },
  { en: "Eight",   tr: "Sekiz", emoji: "8️⃣",  category: "numbers" },
  { en: "Nine",    tr: "Dokuz", emoji: "9️⃣",  category: "numbers" },
  { en: "Ten",     tr: "On",    emoji: "🔟",  category: "numbers" },
  { en: "Zero",    tr: "Sıfır", emoji: "0️⃣",  category: "numbers" },
  { en: "Hundred", tr: "Yüz",   emoji: "💯",  category: "numbers" },
  { en: "First",   tr: "Birinci", emoji: "🥇", category: "numbers" },
  { en: "Second",  tr: "İkinci",  emoji: "🥈", category: "numbers" },
  { en: "Third",   tr: "Üçüncü",  emoji: "🥉", category: "numbers" },

  // ===================== food (30) =====================
  { en: "Apple",      tr: "Elma",       emoji: "🍎", category: "food" },
  { en: "Banana",     tr: "Muz",        emoji: "🍌", category: "food" },
  { en: "Orange",     tr: "Portakal",   emoji: "🍊", category: "food" },
  { en: "Strawberry", tr: "Çilek",      emoji: "🍓", category: "food" },
  { en: "Grape",      tr: "Üzüm",       emoji: "🍇", category: "food" },
  { en: "Watermelon", tr: "Karpuz",     emoji: "🍉", category: "food" },
  { en: "Lemon",      tr: "Limon",      emoji: "🍋", category: "food" },
  { en: "Cherry",     tr: "Kiraz",      emoji: "🍒", category: "food" },
  { en: "Peach",      tr: "Şeftali",    emoji: "🍑", category: "food" },
  { en: "Pear",       tr: "Armut",      emoji: "🍐", category: "food" },
  { en: "Bread",      tr: "Ekmek",      emoji: "🍞", category: "food" },
  { en: "Cheese",     tr: "Peynir",     emoji: "🧀", category: "food" },
  { en: "Egg",        tr: "Yumurta",    emoji: "🥚", category: "food" },
  { en: "Milk",       tr: "Süt",        emoji: "🥛", category: "food" },
  { en: "Water",      tr: "Su",         emoji: "💧", category: "food" },
  { en: "Tea",        tr: "Çay",        emoji: "🍵", category: "food" },
  { en: "Coffee",     tr: "Kahve",      emoji: "☕", category: "food" },
  { en: "Juice",      tr: "Meyve Suyu", emoji: "🧃", category: "food" },
  { en: "Pizza",      tr: "Pizza",      emoji: "🍕", category: "food" },
  { en: "Hamburger",  tr: "Hamburger",  emoji: "🍔", category: "food" },
  { en: "Cake",       tr: "Pasta",      emoji: "🍰", category: "food" },
  { en: "Cookie",     tr: "Kurabiye",   emoji: "🍪", category: "food" },
  { en: "Chocolate",  tr: "Çikolata",   emoji: "🍫", category: "food" },
  { en: "Ice Cream",  tr: "Dondurma",   emoji: "🍦", category: "food" },
  { en: "Soup",       tr: "Çorba",      emoji: "🥣", category: "food" },
  { en: "Salad",      tr: "Salata",     emoji: "🥗", category: "food" },
  { en: "Rice",       tr: "Pilav",      emoji: "🍚", category: "food" },
  { en: "Meat",       tr: "Et",         emoji: "🍖", category: "food" },
  { en: "Carrot",     tr: "Havuç",      emoji: "🥕", category: "food" },
  { en: "Tomato",     tr: "Domates",    emoji: "🍅", category: "food" },

  // ===================== family (12) =====================
  { en: "Mother",      tr: "Anne",     emoji: "👩",  category: "family" },
  { en: "Father",      tr: "Baba",     emoji: "👨",  category: "family" },
  { en: "Sister",      tr: "Kız Kardeş", emoji: "👧", category: "family" },
  { en: "Brother",     tr: "Erkek Kardeş", emoji: "👦", category: "family" },
  { en: "Baby",        tr: "Bebek",    emoji: "👶",  category: "family" },
  { en: "Grandmother", tr: "Büyükanne",emoji: "👵",  category: "family" },
  { en: "Grandfather", tr: "Büyükbaba",emoji: "👴",  category: "family" },
  { en: "Aunt",        tr: "Teyze",    emoji: "👩‍🦱", category: "family" },
  { en: "Uncle",       tr: "Amca",     emoji: "👨‍🦳", category: "family" },
  { en: "Family",      tr: "Aile",     emoji: "👨‍👩‍👧‍👦", category: "family" },
  { en: "Boy",         tr: "Erkek Çocuk", emoji: "👦", category: "family" },
  { en: "Girl",        tr: "Kız Çocuk",   emoji: "👧", category: "family" },

  // ===================== body (15) =====================
  { en: "Eye",      tr: "Göz",     emoji: "👁️", category: "body" },
  { en: "Ear",      tr: "Kulak",   emoji: "👂", category: "body" },
  { en: "Nose",     tr: "Burun",   emoji: "👃", category: "body" },
  { en: "Mouth",    tr: "Ağız",    emoji: "👄", category: "body" },
  { en: "Tongue",   tr: "Dil",     emoji: "👅", category: "body" },
  { en: "Tooth",    tr: "Diş",     emoji: "🦷", category: "body" },
  { en: "Hand",     tr: "El",      emoji: "✋", category: "body" },
  { en: "Foot",     tr: "Ayak",    emoji: "🦶", category: "body" },
  { en: "Leg",      tr: "Bacak",   emoji: "🦵", category: "body" },
  { en: "Arm",      tr: "Kol",     emoji: "💪", category: "body" },
  { en: "Heart",    tr: "Kalp",    emoji: "❤️", category: "body" },
  { en: "Brain",    tr: "Beyin",   emoji: "🧠", category: "body" },
  { en: "Hair",     tr: "Saç",     emoji: "💇", category: "body" },
  { en: "Finger",   tr: "Parmak",  emoji: "👆", category: "body" },
  { en: "Bone",     tr: "Kemik",   emoji: "🦴", category: "body" },

  // ===================== clothes (12) =====================
  { en: "Shirt",    tr: "Gömlek",     emoji: "👔", category: "clothes" },
  { en: "T-shirt",  tr: "Tişört",     emoji: "👕", category: "clothes" },
  { en: "Pants",    tr: "Pantolon",   emoji: "👖", category: "clothes" },
  { en: "Dress",    tr: "Elbise",     emoji: "👗", category: "clothes" },
  { en: "Coat",     tr: "Mont",       emoji: "🧥", category: "clothes" },
  { en: "Scarf",    tr: "Atkı",       emoji: "🧣", category: "clothes" },
  { en: "Gloves",   tr: "Eldiven",    emoji: "🧤", category: "clothes" },
  { en: "Socks",    tr: "Çorap",      emoji: "🧦", category: "clothes" },
  { en: "Shoes",    tr: "Ayakkabı",   emoji: "👞", category: "clothes" },
  { en: "Sneakers", tr: "Spor Ayakkabı", emoji: "👟", category: "clothes" },
  { en: "Boots",    tr: "Çizme",      emoji: "👢", category: "clothes" },
  { en: "Hat",      tr: "Şapka",      emoji: "👒", category: "clothes" },

  // ===================== school (15) =====================
  { en: "School",     tr: "Okul",            emoji: "🏫", category: "school" },
  { en: "Teacher",    tr: "Öğretmen",        emoji: "👨‍🏫", category: "school" },
  { en: "Student",    tr: "Öğrenci",         emoji: "🧑‍🎓", category: "school" },
  { en: "Book",       tr: "Kitap",           emoji: "📚", category: "school" },
  { en: "Notebook",   tr: "Defter",          emoji: "📒", category: "school" },
  { en: "Pen",        tr: "Kalem",           emoji: "🖊️", category: "school" },
  { en: "Pencil",     tr: "Kurşun Kalem",    emoji: "✏️", category: "school" },
  { en: "Eraser",     tr: "Silgi",           emoji: "🩹", category: "school" },
  { en: "Ruler",      tr: "Cetvel",          emoji: "📏", category: "school" },
  { en: "Bag",        tr: "Çanta",           emoji: "🎒", category: "school" },
  { en: "Desk",       tr: "Sıra",            emoji: "🪑", category: "school" },
  { en: "Board",      tr: "Tahta",           emoji: "📋", category: "school" },
  { en: "Lesson",     tr: "Ders",            emoji: "📖", category: "school" },
  { en: "Math",       tr: "Matematik",       emoji: "🧮", category: "school" },
  { en: "Science",    tr: "Fen",             emoji: "🔬", category: "school" },

  // ===================== nature (18) =====================
  { en: "Sun",       tr: "Güneş",   emoji: "☀️", category: "nature" },
  { en: "Moon",      tr: "Ay",      emoji: "🌙", category: "nature" },
  { en: "Star",      tr: "Yıldız",  emoji: "⭐", category: "nature" },
  { en: "Cloud",     tr: "Bulut",   emoji: "☁️", category: "nature" },
  { en: "Rain",      tr: "Yağmur",  emoji: "🌧️", category: "nature" },
  { en: "Snow",      tr: "Kar",     emoji: "❄️", category: "nature" },
  { en: "Wind",      tr: "Rüzgar",  emoji: "💨", category: "nature" },
  { en: "Fire",      tr: "Ateş",    emoji: "🔥", category: "nature" },
  { en: "Tree",      tr: "Ağaç",    emoji: "🌳", category: "nature" },
  { en: "Flower",    tr: "Çiçek",   emoji: "🌷", category: "nature" },
  { en: "Mountain",  tr: "Dağ",     emoji: "⛰️", category: "nature" },
  { en: "Sea",       tr: "Deniz",   emoji: "🌊", category: "nature" },
  { en: "River",     tr: "Nehir",   emoji: "🏞️", category: "nature" },
  { en: "Forest",    tr: "Orman",   emoji: "🌲", category: "nature" },
  { en: "Sky",       tr: "Gökyüzü", emoji: "🌌", category: "nature" },
  { en: "Earth",     tr: "Dünya",   emoji: "🌍", category: "nature" },
  { en: "Rainbow",   tr: "Gökkuşağı", emoji: "🌈", category: "nature" },
  { en: "Leaf",      tr: "Yaprak",  emoji: "🍃", category: "nature" },

  // ===================== home (15) =====================
  { en: "House",      tr: "Ev",          emoji: "🏠", category: "home" },
  { en: "Door",       tr: "Kapı",        emoji: "🚪", category: "home" },
  { en: "Window",     tr: "Pencere",     emoji: "🪟", category: "home" },
  { en: "Bed",        tr: "Yatak",       emoji: "🛏️", category: "home" },
  { en: "Chair",      tr: "Sandalye",    emoji: "🪑", category: "home" },
  { en: "Table",      tr: "Masa",        emoji: "🛋️", category: "home" },
  { en: "Lamp",       tr: "Lamba",       emoji: "💡", category: "home" },
  { en: "Key",        tr: "Anahtar",     emoji: "🔑", category: "home" },
  { en: "Clock",      tr: "Saat",        emoji: "⏰", category: "home" },
  { en: "Phone",      tr: "Telefon",     emoji: "📱", category: "home" },
  { en: "TV",         tr: "Televizyon",  emoji: "📺", category: "home" },
  { en: "Computer",   tr: "Bilgisayar",  emoji: "💻", category: "home" },
  { en: "Bath",       tr: "Banyo",       emoji: "🛁", category: "home" },
  { en: "Soap",       tr: "Sabun",       emoji: "🧼", category: "home" },
  { en: "Toothbrush", tr: "Diş Fırçası", emoji: "🪥", category: "home" },

  // ===================== verbs (15) =====================
  { en: "Eat",     tr: "Yemek",   emoji: "🍽️", category: "verbs" },
  { en: "Drink",   tr: "İçmek",   emoji: "🥤", category: "verbs" },
  { en: "Sleep",   tr: "Uyumak",  emoji: "😴", category: "verbs" },
  { en: "Run",     tr: "Koşmak",  emoji: "🏃", category: "verbs" },
  { en: "Walk",    tr: "Yürümek", emoji: "🚶", category: "verbs" },
  { en: "Read",    tr: "Okumak",  emoji: "📖", category: "verbs" },
  { en: "Write",   tr: "Yazmak",  emoji: "✏️", category: "verbs" },
  { en: "Play",    tr: "Oynamak", emoji: "🎮", category: "verbs" },
  { en: "Sing",    tr: "Şarkı Söylemek", emoji: "🎤", category: "verbs" },
  { en: "Dance",   tr: "Dans Etmek", emoji: "💃", category: "verbs" },
  { en: "Listen",  tr: "Dinlemek", emoji: "👂", category: "verbs" },
  { en: "Look",    tr: "Bakmak",   emoji: "👀", category: "verbs" },
  { en: "Speak",   tr: "Konuşmak", emoji: "🗣️", category: "verbs" },
  { en: "Smile",   tr: "Gülümsemek", emoji: "😊", category: "verbs" },
  { en: "Cry",     tr: "Ağlamak",  emoji: "😢", category: "verbs" }
];
